### ISSUE TITLE
Control window get garbage text if resized

### ISSUE THREAD

**Issue by KeyofBlueS** [v1s1t0r1sh3r3/airgeddon#370] opened 2020-04-28 02:56 UTC
If enterprise control window or evil twin control window are resized, garbage text will be left behind.
I've done a commit (https://github.com/KeyofBlueS/airgeddon/commit/03eedcd4a597b16f8413c2b12118f5c7f21fc5ee) in which if a resize is detected a clear is performed. Work in both xterm and tmux. Window size (columns and lines) are detected through tput command, that is part of the ncurses package (like clear command), so it shouldn't need additional dependencies.
I can submit a pull request if it's ok for you.

Thanks.

**Comment by xpz3** [comment] 2020-04-28 03:01
Hey is this behaviour on dev branch where we did some modifications to the language files or can this be reproduced in the master branch too?

**Comment by KeyofBlueS** [comment] 2020-04-28 03:12
On master too, indeed it has nothing to do with languages.
In order to refresh the control window we use
`echo -ne "\033[K\033[u"`
it doesn't clean the screen though, for a "smoother refresh" I guess.

**Comment by xpz3** [comment] 2020-04-28 03:34
Actually i was referring to the garbage text you told about. I haven't ever tried resizing the window. So was wondering if the garbage text was thrown due to a recent update or not. Understood now. Oscar will update you on this as i usually only run airgeddon in my phone via tmux

**Comment by OscarAkaElvis** [comment] 2020-04-28 08:10
Yeah I tested it and it works. It's uncommon to resize the windows, but if it is done, it's true that maybe depending of the resize it could keep trash printed and with this, that is not happening anymore. It is pushed.

I insist, all of this is much better to discuss on Discord.

Closing.

**Closed by OscarAkaElvis** 2020-04-28 08:10 UTC
Labels: feature enhancement

**Comment by OscarAkaElvis** [comment] 2020-04-28 08:23
Ok, next time ask to us on Discord and then do a PR to our dev branch. We'll accept it in order to you appearing as a contributor on project

**Comment by KeyofBlueS** [comment] 2020-04-28 15:43
I had already asked if I should make a pr, but that's okay, thanks a lot.
