### ISSUE TITLE
Problem with aigeddon

### ISSUE THREAD

**Issue by devilmen80** [v1s1t0r1sh3r3/airgeddon#472] opened 2022-01-15 08:17 UTC
Hello sorry for the disturb.
I am running last version of Manjaro.
Pratically the problem is this:
When I running airmon-ng check kill to put card in monitor mode,network manager, avahi deamon and wpa_supplicant stop their work for one second and after take again the control of my cards. So the command don't work and I cannot run aigeddon.
 Thanks for your work.
Regards

**Comment by cjb900** [comment] 2022-01-15 08:20
aqirmon-check kill is designed to stop service like that for a reason. they do so to prevent background services from interfering with airmon-ng. Also if you are putting the card into monitor mode manually and not with airgeddon that could be part of the issue. it is always recommended to let airgeddon change the mode of the card to prevent any issues.

**Comment by devilmen80** [comment] 2022-01-15 08:24
Thanks for the reply.
With aigeddon is the same.
After few second have running bad Twink i can see Network Manager still active and aigeddon cannot create ap.

**Comment by OscarAkaElvis** [comment] 2022-01-15 10:05
Yeah, it seems the problem is external to airgeddon and is not related directly to it. What I can tell to you is to try airgeddon in other Linux distributions which not have that problem, or investigate further about processes running in your Manjaro. Anyway you could join to Discord channel to try to sort it out there (https://discord.gg/sQ9dgt9). Closing.

**Closed by OscarAkaElvis** 2022-01-15 10:05 UTC
Labels: invalid

**Comment by devilmen80** [comment] 2022-01-15 10:15
> Yeah, it seems the problem is external to airgeddon and is not related directly to it. What I can tell to you is to try airgeddon in other Linux distributions which not have that problem, or investigate further about processes running in your Manjaro. Anyway you could join to Discord channel to try to sort it out there (https://discord.gg/sQ9dgt9). Closing.

Thanks for the reply mate. I am running airgeddon on Kali without any problem so issue is on my Manjaro.
Now i was able to stop all services one for one so i can see airgeddon running on my system but captive portal show me invalid password while it is correct. Its strange. I can see passwd on the top of window...but nothing more. Thanks

**Comment by OscarAkaElvis** [comment] 2022-01-15 10:17
if the password has strange characters, that could be "normal". I mean, airgeddon is filtering some special chars in order to avoid to be hacked using an injection from the portal. There is a plugin to disable that security feature. Check this:

https://github.com/OscarAkaElvis/airgeddon-plugins

Just copy the `allchars_captiveportal.sh` into the airgeddon plugins dir to enable it. Cheers.

**Comment by devilmen80** [comment] 2022-01-15 10:22
> if the password has strange characters, that could be "normal". I mean, airgeddon is filtering some special chars in order to avoid to be hacked using an injection from the portal. There is a plugin to disable that security feature. Check this:
> 
> https://github.com/OscarAkaElvis/airgeddon-plugins
> 
> Just copy the `allchars_captiveportal.sh` into the airgeddon plugins dir to enable it. Cheers.

Still really thanks for your work.
Password is just of 6 numbers nothing special...
I'm testing on my network..
Anyway I will follow your advice .
Thanks.

**Comment by OscarAkaElvis** [comment] 2022-01-15 10:23
That is not possible. Minimum length for a WPA/WPA2 password is 8, so you pass can't be just 6 numbers. Are you sure about the password? I think you are wrong man! 🙄

**Comment by devilmen80** [comment] 2022-01-15 10:27
> Non è possibile. La lunghezza minima per una password WPA/WPA2 è 8, quindi il tuo pass non può essere composto solo da 6 numeri. Sei sicuro della password? Penso che tu abbia torto uomo!🙄

Yes i was wrong to write...passwd is of 8 numbers..i try many time...but nothing. Thanks

**Comment by OscarAkaElvis** [comment] 2022-01-15 10:33
I insist. I suggest to you to connect to our Discord channel to continue this further. For sure you'll need to provide screenshots because it works for everybody and it should work for you. airgeddon is taking the password entered in the captive portal, is creating a dict with only that word and testing the pass against the handshake/pmkid you entered before the attack. As a result of it, it will know if is the right password or not. If it is not, it will show to the user (the victim) a warning about the password is not the right one, and for the attacker it will be shown as a password attempt. If is the right password, it will show a message to the user (victim) saying that internet connection will be reestablished and for the attacker, the attack will stop showing the right password and saying that it was saved in the location you previously set.

It works for everybody, so it should work for you. Otherwise, you have something "weird". Connect to Discord and explain your network type (WPA, WPA2). Try an offline dictionary attack using hashcat or aircrack from the menu of offline cracking setting as a dict a file just containing the password you are typing over the handshake/pmkid you are selecting for the Evil Twin attack. It should crack it flawlessly, just to be sure that everything is working... and more tests can be done.

**Comment by devilmen80** [comment] 2022-01-15 10:37
> I insist. I suggest to you to connect to our Discord channel to continue this further. For sure you'll need to provide screenshots because it works for everybody and it should work for you. airgeddon is taking the password entered in the captive portal, is creating a dict with only that word and testing the pass against the handshake/pmkid you entered before the attack. As a result of it, it will know if is the right password or not. If it is not, it will show to the user (the victim) a warning about the password is not the right one, and for the attacker it will be shown as a password attempt. If is the right password, it will show a message to the user (victim) saying that internet connection will be reestablished and for the attacker, the attack will stop showing the right password and saying that it was saved in the location you previously set.
> 
> It works for everybody, so it should work for you. Otherwise, you have something "weird". Connect to Discord and explain your network type (WPA, WPA2). Try an offline dictionary attack using hashcat or aircrack from the menu of offline cracking setting as a dict a file just containing the password you are typing over the handshake/pmkid you are selecting for the Evil Twin attack. It should crack it flawlessly, just to be sure that everything is working... and more tests can be done.

Ok I will follow your advice.
Thanks a lot for your support.
You are great!
Regards.
