### ISSUE TITLE
ssl strip error

### ISSUE THREAD

**Issue by AkumaBiNoTori** [v1s1t0r1sh3r3/airgeddon#351] opened 2020-03-16 00:47 UTC
it says the sslstrip error and when it says download dependencies it takes time then it gives this message  "An error occurred while trying to install dependencies. This may be due to multiple causes. Make sure your internet connection is working. Anyway, you have installed all essential tools so you can continue. You'll miss only some features"

**Comment by xpz3** [comment] 2020-03-16 02:52
You didn't fill up the issue template. Its there for a reason. No screenshots. If the auto installation of dependency fails, try installing them manually and see what error occurs. For further questions, join the discord channel.
https://discord.gg/sQ9dgt9
Closing

**Closed by xpz3** 2020-03-16 02:52 UTC

**Comment by OscarAkaElvis** [comment] 2020-03-16 18:38
There is a bug happening only in Kali Linux and BlackArch (is not reproducible in Parrot Linux). It ocurrs when the plugin try to auto install more than one dependency at once. This has been fixed and it will be released with the next v10.10.

You can see the commit with the fix here: https://github.com/v1s1t0r1sh3r3/airgeddon/commit/1cd9d191abfda728dc7efe4aed7268279b2d2151

So you can use the dev branch or wait until it is released (it will be pretty soon), or just install them manually before launching airgeddon.

For further discussion, join discord as @xpz3 said. Thanks.

**Comment by D4rkX0** [comment] 2020-04-12 21:04
This is the fix:

sudo apt-get install python-twisted-web
https://github.com/moxie0/sslstrip.git
cd sslstrip
python setup.py install

**Comment by OscarAkaElvis** [comment] 2020-04-13 07:16
But.... what is the point @D4rkX0 , sslstrip package was removed from kali repos or something? Because the way to install it used to be as simple as `apt install sslstrip`.

**Comment by KeyofBlueS** [comment] 2020-04-13 07:24
For sure it was removed from debian https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=951818

**Comment by OscarAkaElvis** [comment] 2020-04-13 07:50
Yeah but I wasn't unsure about what Linux distro we are talking about... the guy who started this thread didn't specify anything... that was the reason of closing it and tagging it as "invalid". I tested it right now and I see it disappeared from Kali and Parrot.

Anywya, you have a deb package available here at one v1s1t0r's repo: https://github.com/v1s1t0r1sh3r3/sslstrip/blob/master/sslstrip_0.9-1kali3_all.deb

Just download and install it using dpkg. `dpkg -i sslstrip_0.9-1kali3_all.deb`

**Comment by v1s1t0r1sh3r3** [comment] 2020-04-13 11:41
Anyway, we are not in charge of package maintaining on repos for third party tools. All we can say from airgeddon is:

This is the dependency needed.
This is how it is usually installed.
Good luck.

**Comment by D4rkX0** [comment] 2020-04-13 23:56
> 
> 
> But.... what is the point @D4rkX0 ? , sslstrip package was removed from kali repos or something? Because the way to install it used to be as simple as `apt install sslstrip`.

yeah the apt can't get the package any more :/

**Comment by OscarAkaElvis** [comment] 2020-04-23 12:25
Check this:

https://github.com/v1s1t0r1sh3r3/airgeddon_deb_packages

**Comment by OscarAkaElvis** [comment] 2020-12-29 09:25
This won't be a problem for the next release v10.40 on which ssltrip dependency is removed.
