### ISSUE TITLE
line:779: Parse error near `('

### ISSUE THREAD

**Issue by Katastrofa0** [v1s1t0r1sh3r3/airgeddon#553] opened 2023-08-12 12:24 UTC
![2](https://github.com/v1s1t0r1sh3r3/airgeddon/assets/119258885/4978d320-b805-4cf2-9d31-8c6fba9ce640)

It worked fine quite recently, but today we launched such an error. What is the reason for this? Reinstalled several times, does not help. The source code is original

**Comment by OscarAkaElvis** [comment] 2023-08-12 12:33
Hi, in order to be able to help you, you must fill all the data on the issue creation template. what is your OS?, what airgeddon version are you using?, etc. because I have other stuff on my line 777. It may vary depending on the version.

What are the reproduction steps to generate the error? just launch it and the error appear? that can't be. All versions of airgeddon are 100% working. Maybe you messed it up line endings. Maybe you have \r\n instead of just \n at the end of each line. That usually happens when you are working on Windows. Did you download it on a windows? how are you installing airgeddon? via apt? git cloning?. Please, describe the steps exactly. Something like 1. I do this command `git clone (https://github.com/v1s1t0r1sh3r3/airgeddon` , 2. cd airgeddon, 3. `bash airgeddon.sh`.

I'll close this because our policy is that if you don't have time to read the requirements to open an issue (just 30 secs of your time while creating it, is the text appearing in the fields that you deleted), we don't have time to help you. But this time I'll tell you that if you want more help, you can join to our Discord server for further discussion. Invitation link is in contact section at wiki.

Cheers.

**Closed by OscarAkaElvis** 2023-08-12 12:33 UTC
