### ISSUE TITLE
Problem with bettercap

### ISSUE THREAD

**Issue by Nafuiss** [v1s1t0r1sh3r3/airgeddon#473] opened 2022-01-26 20:58 UTC
Every time I go to do an Evil Twin attack using option 7 or 8, this error appears in bettercap:

`[15:54:38] [sys.log] [war] Could not detect gateway.`
`192.169.1.0/24 > 192.169.1.1  Â» [15:54:38] [sys.log] [err] error while running caplet /tmp/ag.bettercap.cap: exit status 4`

Does anyone know how I can resolve this? Other things work normally. Only the bettercap is having a problem.

The bettercap version is v2.29. I'm running airgeddon on parrot security 4.11.3

**Comment by OscarAkaElvis** [comment] 2022-01-27 08:52
I think the "could note detect gateway" message is normal... what is not normal is your error about the cap file. I tested it and I got the first "could not detect gateway" warning but everything is working fine.

![image](https://user-images.githubusercontent.com/5803348/151320939-7382e2a9-1d7e-4cd7-a7c6-3cce7f79cda0.png)

As you can see, I'm also using bettercap 2.29, so that is not the problem. I'm using parrot security OS as well.

Everything is working fine for me... as you can see on next image, sslstrip2 is enabled... Plain text creds capturing is also working (captured fake ftp creds to test)

![image](https://user-images.githubusercontent.com/5803348/151324176-7cad0170-fc36-47ab-939f-75e1e68d9e56.png)

For some reason, your .cap fine is not working well... you should copy during the attack your /tmp/ag.bettercap.cap file to other location or put its content here to check if it is ok.

Anyway, we (airgeddon staff) prefer to discuss complex stuff on our Discord channel. Faster response, more people helping, etc... so feel free to join here: https://discord.gg/sQ9dgt9

**Comment by Nafuiss** [comment] 2022-01-27 15:34
I've tried running all the commands by hand, and it displays this:

![Airgeddon](https://user-images.githubusercontent.com/87517040/151390857-ef0ae8bc-fb1e-418b-b250-e3566ac97daf.png)

**Comment by OscarAkaElvis** [comment] 2022-01-27 15:53
Your cap file is well constructed, is ok. Regarding the commands... it seems like your port 8080 maybe is already being used by another process or something like that.

As far as I know, there is already a check in airgeddon to verify if needed ports are free and ready before launch an attack. That checks were implemented in airgeddon v10.42. I'm not sure about your airgeddon version because you didn't fill the issue template correctly, something that usually cause that the issue is closed immediately. For some reason not this time, but please, next time be sure to follow the rules because the issue template filling is mandatory and save time to us to be asking basic stuff to the OP, like in this case....

What is your airgeddon version? if is not v10.42, please update it. In v10.42 the check is done, but in v11.00 it shows even the name of the conflicting process. v11.0 is not released yet but is available at dev branch, you can check and test it. I bet you have and old airgeddon version. Otherwise the port check should not let you continue to launch attack.

**Comment by OscarAkaElvis** [comment] 2022-01-27 16:06
Maybe is not a problem of free port.... maybe is something on bettercap. It seems this is beyond the airgeddon support. As you can see other users reported it on bettercap's Github:

https://github.com/bettercap/bettercap/issues/909

In fact, the second guy is showing his config and it's exactly the same generated by airgeddon, every single char. So probably is an airgeddon user.

I'll close this issue because as I said it's an external to airgeddon error. If the same config is working for some people and not working for other.... maybe you have something in your O.S. causing it. Continue on that Bettercap's threat and good luck.

**Closed by OscarAkaElvis** 2022-01-27 16:06 UTC
Labels: waiting for info
