### ISSUE TITLE
Captive portal with internet access not working

### ISSUE THREAD

**Issue by usama7628674** [v1s1t0r1sh3r3/airgeddon#287] opened 2019-08-15 02:31 UTC
#### What is your airgeddon version?

 9.21 

#### What is your Linux O.S. and which version?

Kali Linux 2019.2

#### Which is the chipset of your wireless card?

1) Atheros AR9271 (ath9k_htc)
2) Atheros QCA9565 / AR9565 (ath9k)

#### Describe the issue and the steps to reproduce it

I have two adapters with two interfaces wlan0 and wlan1,wlan0 is connected to internet and wlan0 is not connected to internet.I put wlan1 in monitor mode using airgeddon and use **option 7 Evil twin attacks menu** then **option 9 Evil Twin AP attack with captive portal (monitor mode needed)** and select target and all necessary steps that the tool dumps on terminal.I used **N for dos pursuit mode** and **Y for internet access method** then i selected wlan0 which is already connected to internet and then when airgeddon launches xterm windows my wlan0 interface changed its state to managed mode and i'm no longer connected to internet and so i could not browse internet or redirect to captive portal using android device when i'm connected to fake AP that airgeddon creates.

I've three interfaces now
mon0 - which mdk4 use to deauth clients on AP
wlan1 - which is in master mode cuz hostapd is using this interface to create fake AP.
wlan0 - which is in managed mode and and no longer connected to internet.

**Comment by OscarAkaElvis** [comment] 2019-08-15 10:42
Hi, not sure to understand correctly what you are trying. It is supposed that if you select one adapter to perform the attack, the other adapter with internet access must be another completely different and don't used in the attack (just to have internet access).

The captive portal is going to "cut" the internet access of the clients, it has two methods. One (better in my opinion) is to use dnsspoof to perform the "DNS blackhole" in order to redirect all the DNS requests of the clients to the portal. The other one is to have internet access just for the DNS resolution.

The card used in the attack is going to be "splitted" into two logical interfaces. One to set the fake AP which needs to be in managed mode before passing to master mode and the other part will be in monitor mode just to perform DoS attack. That is possible because both are going to work on the same channel and airgeddon is handling it for you. At the end of the attack, airgeddon is going to restore the initial state of your card (managed or monitor) and remove the split. Regarding the secondary interface just to give internet access, no action is taken on it, so it makes no sense that if you are losing internet access on it... maybe it could be happening if Network Manager is killed and that could affect to your "global" internet access.

I'll try to reproduce this, but I guess I will not be able. As a workaround use the dnsspoof method which seems a more solid option. Only needs one more dependency to work (dsniff package). If you could provide more details, it could be great in order to reproduce the problem. Bear in mind that captive portal is working since a lot of versions and no changes were made on it... maybe an external element could affect to its behavior (like Network Manager).

Let me check this closer and provide more info if possible. Also let us know if is fully working for you using the dnsspoof option. Thanks.

**Comment by v1s1t0r1sh3r3** [comment] 2019-08-17 09:54
I reproduced the problem. Probably it is failing since recent changes on nftables.

Anyway, it makes no sense to have the internet access method knowing that dnsspoof method is much better. I'll do some changes in order to let only the dnsspoof method working on captive portal attack. Thanks for the report.

**Comment by usama7628674** [comment] 2019-08-17 10:08
@v1s1t0r1sh3r3 What about captive portal with sniffing,captive portal with bettercap and sslstrip?These options are also not working.
I overcome this issue by manually connecting to network using wpa_supplicant.

**Comment by v1s1t0r1sh3r3** [comment] 2019-08-17 11:12
There is no captive portal with bettercap. Bettercap is used only in BeEF attack.

I'm removing the internet access method for captive portal attack. Now captive portal attack will have only the dnsspoof method. All the remaining (non-captive-portal) evil twin are working fine. I did a test over all of them a few moments ago.

**Comment by OscarAkaElvis** [comment] 2019-08-17 18:14
There is only one captive portal Evil twin attack. The rest of the evil twin attacks (all of them) need internet access as normal (no dnsspoof tool involved) and they are working fine. Only the captive portal evil twin attack with internet access for the dns resolution was failing and it will be removed leaving only dnsspoof captive portal which works like a charm.

**Comment by v1s1t0r1sh3r3** [comment] 2019-08-18 08:24
Done. It will be released on next v9.22. Closing.

**Closed by v1s1t0r1sh3r3** 2019-08-18 08:24 UTC
Labels: bug
