### ISSUE TITLE
Incorrect definition of the OS

### ISSUE THREAD

**Issue by BlitGaming** [v1s1t0r1sh3r3/airgeddon#477] opened 2022-02-03 07:49 UTC
#### What is your airgeddon version?
**v10.42** or **v.11.0**

#### What is your Linux O.S. and which version?
![Screenshot_20220203_144427](https://user-images.githubusercontent.com/79034202/152301407-594f293d-11c7-4949-bd93-c0fedb9e1c89.png)
I have a laptop.

#### Which is the chipset of your wireless card?
Information from lspci:
**09:00.0 Network controller: Qualcomm Atheros AR9285 Wireless Network Adapter (PCI-Express) (rev 01)**

#### Describe the issue and the steps to reproduce it
The operating system assumed by the program is detected as "Unknown Linux", although I use Arch and it is listed as supported.
![image](https://user-images.githubusercontent.com/79034202/152301885-1884a88c-4ea2-4598-8e4e-83dadeaefcb0.png)

**Comment by BlitGaming** [comment] 2022-02-03 07:53
I tried installing the latest version of airgeddon as a binary package, but the display is still incorrect. Before that, I installed it from the BlackArch repositories.

**Comment by OscarAkaElvis** [comment] 2022-02-03 08:36
Ok... on BlackArch repos latest is 10.42 but a few days ago we released 11.0 . It could take some days before BlackArch staff bump it into their repos... so soon it will be also v11.0.

Anyway... I use BlackArch and in my case is well detected as you can see on next image... 

![image](https://user-images.githubusercontent.com/5803348/152306857-4cfb8d52-493a-4744-9dec-179b3a54674e.png)

Let's check how airgeddon detects OS for BlackArch case... the first phase of detection is based on the output of `uname -a` command. Can you share what is shown there to you?

I recommend to you to join to Discord channel for further support: https://discord.gg/sQ9dgt9

**Comment by BlitGaming** [comment] 2022-02-03 08:45
![image](https://user-images.githubusercontent.com/79034202/152309557-b37e5381-9e45-4b88-ad7e-02b27407a4d7.png)

**Comment by BlitGaming** [comment] 2022-02-03 08:48
Why can't use the /etc/os-release file to determine the distribution?
![image](https://user-images.githubusercontent.com/79034202/152309977-f3054f15-fc0b-4a9b-ba82-535a233ee7c7.png)

**Comment by OscarAkaElvis** [comment] 2022-02-03 08:57
You are so fast my friend... I said "the first phase of detection"... so first, `uname -a` is checked. Usually is enough to detect it correctly.... then if is not finally detected (like in your case)... the second phase consist in to check different files on /etc. 

This is the airgeddon code for BlackArch detection

![image](https://user-images.githubusercontent.com/5803348/152310693-b3d452e0-8429-4dfe-8e31-832f5107af84.png)

It is ok... so the problem is that your BlackArch is not "standard" for whatever reason... I think we don't need to do anything in airgeddon side... as you can see, BlackArch is not shown in your OS... neither in `uname -a` output nor in `/etc/os-release` file... so the problem is in your side. We can't "invent" that is a BlackArch if it is not shown anywhere. Not sure how you have that configuration because as I said I have BlackArch and it is ok for me (and for the rest of human beings).

You can "trick" your OS setting "BlackArch Linux" on PRETTY_NAME of your /etc/os-release file if you want.

Closing.

**Closed by OscarAkaElvis** 2022-02-03 08:57 UTC
Labels: waiting for info
