### ISSUE TITLE
opt/airgeddon/airgeddon.sh: line 14444: ps: command not found

### ISSUE THREAD

**Issue by Dave3991** [v1s1t0r1sh3r3/airgeddon#312] opened 2019-10-08 13:44 UTC
#### What is your airgeddon version?

v9.23

#### What is your Linux O.S. and which version?

Ubuntu 18.04.3 

#### Which is the chipset of your wireless card?

Intel dual band wireless AC 8265 
Thinkpad t480

#### Describe the issue and the steps to reproduce it

Error: opt/airgeddon/airgeddon.sh: line 14444: ps: command not found

How to reproduce:
Put interface in monitor mode -> Explore for targets (monitor mode needed)

**Comment by xpz3** [comment] 2019-10-08 14:45
Are you using tmux instead of xterm? Did you try apt-get update && apt-get install -y procps

**Comment by OscarAkaElvis** [comment] 2019-10-08 14:54
There is no validation for ps assuming that all Linux have ps command by default... but I see that is not always... what kind of ubuntu are you using which it hasn't ps command by default?

Maybe we can add it for initial checks as essential tool. As @xpz3 said, on debian based distros it can be installed by apt . It is in procps package.

**Comment by OscarAkaElvis** [comment] 2019-10-08 15:50
Ok ... that is a detail you should mentioned from the beginning IMO.

What image are you using? are you building your own Docker image from scratch? because AFAIK, if you use the Dockerfile provided by airgeddon's repo or the already built image from Dockerhub, it is based in parrot image and it contains the needed stuff including ps command.

Is ubuntu your host O.S ? or is your docker image based in Ubuntu?

**Comment by OscarAkaElvis** [comment] 2019-10-08 16:10
Ok then... it seems there must be some kind of problem with the parrot's docker image on which we are basing airgeddon's image. It used to have ps command by default but for some reason that base image changed and now it seems it doesn't have the ps command installed by default. The problem is not in our side (airgeddon's side) but is affecting to all of us. I'll notify that to the parrot's image maintainer.

If you are using a docker run command, you are not using our Dockerfile to build it. You are using the already built image from Dockerhub. I must add that previous docker pull command is not needed because launching docker run command will download the image if it is not existing locally.

Anyway, to avoid this to happen anymore, we'll add a validation for ps command as essential tool at the beginning of the dependencies check and of course i'll add it to Dockerfile.

I'll tag this as "compatibility enhancement" more than a bug because is not clearly a bug from our side. Thanks for the report. You'll see the changes on the next v10.0 . It will still take some time to be released... so if you want to use docker you should download the repo and build your own image adding the apt install procps statement on the Dockerfile before building it. Or maybe you could want to wait for a while and check commit that will be done soon (probably today at plugins system branch) and then use that Dockerfile version to build it using `docker build -t my_custom_airgeddon_image .`

Closing.

**Closed by OscarAkaElvis** 2019-10-08 16:10 UTC

**Comment by OscarAkaElvis** [comment] 2019-10-08 16:14
Done. Now you can check Dockerfile from plugins_system branch and use it to build the image which will include the missing ps command.
