### ISSUE TITLE
Cannot recognize network interface on "Interface Selection" menu (empty value)

### ISSUE THREAD

**Issue by beerkala** [v1s1t0r1sh3r3/airgeddon#100] opened 2017-09-09 03:18 UTC
#### What is your airgeddon version?

7.2 

#### What is your Linux O.S. and which version?

Kali Rolling

Bash version (4.4.12(1)-release)

#### Which is the chipset of your wireless card?

Realtek RTL8812AU 

#### Describe the issue and the steps to reproduce it

I have installed the `realtek-rtl88xxau-dkms` driver.

When i run airgeddon.sh, it displays the following on the **Interface selection** menu:

```
Select an interface to work with : 
--------- 
1.  eth0 // Chipset: Intel Corporation 82545EM
2.  wlan0 // Chipset:  

```

It can't recognize the `wlan0` name and fails on next step

```
---------
2.  Put interface in monitor mode 
---------
```

Step 2 will fail, I need to manually run `iwconfig wlan0 mode monitor`, in order to proceed.

**Comment by beerkala** [comment] 2017-09-09 03:21
maybe fix it on 
function iwconfig_fix() {

	debug_print

	iwversion=$(iwconfig --version 2> /dev/null | grep version | awk '{print $4}')
	iwcmdfix=""
	if [ "${iwversion}" -lt 30 ]; then
		#iwcmdfix=" 2> /dev/null | grep Mode: "
	fi
}

**Comment by v1s1t0r1sh3r3** [comment] 2017-09-09 09:30
Hi. Are you sure you are launching airgeddon as root or using sudo? Try that.

On new 7.21 version which is under development now is mandatory to be root or use sudo to avoid this kind of problems. You can try it downloading the `dev` branch. `git clone -b dev https://github.com/v1s1t0r1sh3r3/airgeddon.git`

Are you sure your driver is well installed? are you able to use your wireless network card as normal? I mean, to connect to a network and surf the web using it.

Regarding your suggestion, iwconfig_fix function is ok. Which is your wireless tools version? 29? 30? you can show it doing `iwconfig --version`. I guess you'll have version 30 because is what Kali is using. This shouldn't be a problem. I think your problem is more focused on permissions. Anyway, I can't reproduce your problem. I don't have a wireless card with that Chipset.

Summarizing:
Use root or sudo
Try 7.21 from dev

Let us know the results.

**Comment by beerkala** [comment] 2017-09-09 09:47
iwconfig
wlan0mon  IEEE 802.11  Mode:Monitor  Frequency:2.462 GHz  Tx-Power=12 dBm   
          Retry short limit:7   RTS thr:off   Fragment thr:off
          Power Management:off
          
eth0      no wireless extensions.

wlan0     IEEE 802.11  Mode:Monitor  Frequency:2.462 GHz  Tx-Power=12 dBm   
          Retry short limit:7   RTS thr:off   Fragment thr:off
          Power Management:off
          
lo        no wireless extensions.

iwconfig --version
iwconfig  Wireless-Tools version 30
          Compatible with Wireless Extension v11 to v22.

Kernel    Currently compiled with Wireless Extension v22.

wlan0mon  Recommend Wireless Extension v21 or later,
          Currently compiled with Wireless Extension v22.

wlan0     Recommend Wireless Extension v21 or later,
          Currently compiled with Wireless Extension v22.



root@kali:/home/tools/airgeddon# airmon-ng start wlan0


PHY	Interface	Driver		Chipset

phy0	wlan0		8812au		 

		(mac80211 monitor mode already enabled for [phy0]wlan0 on [phy0]10)


i have try down 7.21 from dev,the problem is still .

Interface You already have a wlan0 device but it is NOT in station mode. selected. Mode: (Non wifi card) 
need to manually run
 ifconfig wlan0 down 
 iwconfig wlan0 mode monitor
ifconfig wlan0 up

Another question how to cheking the wifi card status is normal Capture Handshake ? include airgeddon.sh ?
I am testing many times,some times the capture display fix wlan0 chanel (number).
Tks!

**Comment by v1s1t0r1sh3r3** [comment] 2017-09-09 11:38
It seems we are messing and mixing things. You said "step 2 will fail" trying to put monitor mode. What error are you getting? Can you put a screenshot of the error?

On the other hand, it seems you have at same time wlan0 and wlan0mon. Don't plug 2 wireless cards at the same time or you could have errors.

You didn't answered yet to one of the questions I did. Can you connect as normal with that wifi card to a wireless network and surf without problems?

**Comment by beerkala** [comment] 2017-09-09 16:38
finaly,i have reslove this question.
i use the tp-link wdn6200 ,it's use rtl8812au. And install the kali rolling driver.
apt-get install realtek-rtl88xxau-dkms (https://bugs.kali.org/view.php?id=3260 and https://github.com/astsam/rtl8812au)
**open wifi monitor run**
ifconfig wlan0 down && macchanger -r wlan0 && iw reg set GY && airmon-ng check kill && iwconfig wlan0 mode monitor && ifconfig wlan0 up && airmon-ng && airmon-ng start wlan0
**close monitor run**
ip link set wlan0 down && iwconfig wlan0 mode managed && ip link set wlan0 up && service networking restart && service network-manager restart

i modify it on myself airgeddon.sh ,it like some problem. but it can run normal.
Hope you conform this to airgeddon.sh,this will be good news for use rtl8812au or rtl8814au user.
TKS!

**Comment by v1s1t0r1sh3r3** [comment] 2017-09-09 16:45
So finally it was a driver problem I guess. Not related to airgeddon. Hard to understand your english :smile: . Closing.

**Closed by v1s1t0r1sh3r3** 2017-09-09 16:45 UTC
Labels: waiting for info

**Comment by OscarAkaElvis** [comment] 2019-11-11 21:24
Ding ding ding!!! your dreams come true: https://github.com/OscarAkaElvis/airgeddon_realtek_chipset_fixer
