### ISSUE TITLE
Evil Twin kills main wifi connection

### ISSUE THREAD

**Issue by edspiner** [v1s1t0r1sh3r3/airgeddon#126] opened 2018-04-18 08:45 UTC
#### What is your airgeddon version?

8.01

#### What is your Linux O.S. and which version?

Kali Linux 2018.3? (up to date from kali-roing repo)

#### Which is the chipset of your wireless card?

RTL8188CUS

#### Describe the issue and the steps to reproduce it

https://github.com/v1s1t0r1sh3r3/airgeddon/blob/ae4a1e39635b35ee0ac7fcb25f19e99b71631b0b/airgeddon.sh#L6027

I'm not sure if this is ultimately required here - but i presume it also can be enclosed in the:
`if [ "${check_kill_needed}" -eq 1 ]; then`

**Comment by OscarAkaElvis** [comment] 2018-04-18 09:10
As the var name says... it's only done if needed. That is based on your NetworkManager version.

Which is your NetworkManager version? What is your OS? What is your airgeddon version? Please fill up all the needed questions on the template when open an issue.

**Comment by OscarAkaElvis** [comment] 2018-04-18 12:11
It's suppossed that if you have a Network Manager greater than 1.0.12 , airgeddon detects it and it's not needed to execute the check kill command, so internet is not lost.

To check your network manager version execute: `NetworkManager --version` and tell to us the version you have.

**Comment by edspiner** [comment] 2018-04-18 19:30
Hi sorry for non professional issue issue report. Fixed.

the line i pointed in comment is not enclosed within the mentioned if var. All other places where you run `airmon-ng check kill` are so this is why i reported this as issue. Correct me if i'm wrong.

**Comment by v1s1t0r1sh3r3** [comment] 2018-04-18 20:44
No, that's not a bug. This is intentionally. The avoid of executing `airmon-ng check kill` is only to put interface on monitor mode. Nothing to do about any Evil Twin while using `hostapd`. It doesn't work without the check kill. Anyway, I tested it again hoping something changed among versions... but same result, so it must be as it is, sorry.

Closing

**Closed by v1s1t0r1sh3r3** 2018-04-18 20:44 UTC
Labels: waiting for info
