### ISSUE TITLE
AP Mode Not Enabled

### ISSUE THREAD

**Issue by azamet90** [v1s1t0r1sh3r3/airgeddon#194] opened 2018-11-07 20:51 UTC
#### What is your airgeddon version?

8.12

#### What is your Linux O.S. and which version?
latest

#### Which is the chipset of your wireless card?

alfa that model which is ending with ACH

#### Describe the issue and the steps to reproduce it
i want to try last time my luck before i lost my hope with this application :D 
internal wifi works without problem but on alfa wifi adapter AP is not creating what can the reasons if i can manually create ap the same thing happens on other applications in github too but manually i can create ap point and but i cant connect it with my phone what do i need to set up for the ap mode?

PLEASE HELP ME ABOUT İT İF SOMETHİNG İS ON MY SİDE WRONG

my only problem is ap mode right now

**Comment by v1s1t0r1sh3r3** [comment] 2018-11-07 20:58
Please don't open issues without any control. You have already another issue (even if it is closed) to discuss anything: https://github.com/v1s1t0r1sh3r3/airgeddon/issues/191

To open more issues are not going to change the answers. I repeat, this problem is not related to airgeddon. If you have one card fully working and other different card with issues... why do you think is airgeddon related issue? the most probably is that the problem is to be related to your card, driver or whatever. I told you on the other thread, is a known related problem between hostapd software (hostapd software is not airgeddon is a third party tool that airgeddon use to create APs) and your card driver. Even I put on the other thread an alternative solution giving to you a link of a custom hostapd software which was modified by someone in order to be compatible with your card. Did you isntalled it? did you tested it?

Last warning for you, we ARE NOT a wireless helpdesk support. We support ONLY airgeddon software.

Closing and locking this.

**Closed by v1s1t0r1sh3r3** 2018-11-07 20:58 UTC
