### ISSUE TITLE
Kali Linux iptables1.8.2 issue

### ISSUE THREAD

**Issue by xpz3** [v1s1t0r1sh3r3/airgeddon#219] opened 2019-01-22 22:54 UTC
#### What is your airgeddon version?

The current latest version pulled from github 8.12

#### What is your Linux O.S. and which version?

Kali Linux 2019.1, kali-rolling repository using LinuxDeploy on rooted phone

#### Which is the chipset of your wireless card?

ath9k_htc

#### Describe the issue and the steps to reproduce it

Im trying to use captive portal. It's working good but there is a problem with IPtables. Im having 1.8.2 version of IPtables so dports option isn't working. while starting captive portal,its showing error msg like --dports argument is invalid. iptables-legacy is present and it should work. do I need to change the source code of airgeddon to replace any IPtables with iptables-legacy or is it a known issue having a solution? I don't know how to switch back to 1.6 version of iptables

**Comment by xpz3** [comment] 2019-01-23 01:58
I'd like to add by saying that I'm able to capture passwords even with IPtables not working but I need to disable my phone's wifi or mobile data connection. If I leave the wifi or mobile data on, the captive portal doesn't work, that is, on the client side fake page redirection will not happen. If I turn of the wifi and mobile data, the fake page loads and captures the password.
I'd like to know whether this issue is caused by the IPtables not being able to set forwards. 
Anyway very nice script.

**Comment by OscarAkaElvis** [comment] 2019-01-23 11:16
Hello, if you are using "strange devices" like LinuxDeploy arm or similar stuff and your iptables are old... I can suggest you to update them to use standard iptables. As you can imagine we are not going to do code modifications only for that specific case. Anyway, if using `iptables-legacy` instead of `iptables`, you can try on your own to replace the iptables commands. If I can remember well, all of them are concentrated in just few functions:

save_iptables
restore_iptables
clean_iptables
set_std_internet_routing_rules

You can modify the code of that functions in order to make it work with your iptables-legacy commands. And probably you'll need (to bypass the dependency check) to modify the `optional_tools_names` array and replace also iptables there.

I'm going to close this because it is not a bug. But anyway, feel free to ask here. We can try to help. Regards.

**Comment by xpz3** [comment] 2019-01-23 12:19
Actually the IPtables are not old. It's in fact the latest version installed from kali repository. The problem with latest version is that it's usage have changed. I think anyone installing kali Linux on laptop from the latest repository will arrive at the same scenario. The resolution I think would be to change the source code to iptables-legacy, iptables-legacy-save etc or switch to an older version of IPtables like 1.6.2. Another possible solution would be to rename iptables-legacy to IPtables and remove the original IPtables binary file. I don't know whether the last one would work or not.
I came across the same issue with another similar tool. I posted this just in case anyone running into the same scenario would be benefited.
I think arm devices are becoming prominent now a days and a tool like airgeddon would be very easy to use on a supported mobile device than a laptop. 
I want to mention that it was very easy to setup airgeddon tool on my mobile device and Im able to capture passwords with ease and above all everything fits in my pocket...! Thanks for the tool anyways.

**Comment by OscarAkaElvis** [comment] 2019-01-23 14:13
Sorry but I'm not able to reproduce it. I have a Kali fully upgraded. It has iptables and iptables-legacy installed. Both of them are v1.8.2

![image](https://user-images.githubusercontent.com/5803348/51612014-e7ce9200-1f20-11e9-92fd-adfcc801d935.png)

I launched captive portal on v8.12 and everything was working fine. I modified all the code replacing the mentioned above functions in order to use iptables-legacy instead of iptables and I did another test.... and everything worked fine again. No errors... I connected in both cases to the fake created network and all were fine.

Hmmm..... maybe the main difference is that my Kali is amd64 standard and you are testing in an ARM environment... I have also a OnePlus 3 with LinuxDeploy. I'll try to install Kali and once fully upgraded to the latest stuff I'll try to reproduce it... but I guess I'll need for that an OTG cable to plug an Alfa wireles card to the phone.... I'll try to reproduce it, but too much work for a very very rare scenario my friend... can you test on other standard kali? I bet that it will work flawlessly.

**Comment by xpz3** [comment] 2019-01-23 14:18
Yes on standard kali it's working fine. I tried IPtables command on my phone and dports error shows up. No need to try on airgeddon. Reproduce with oneplus3- Linux deploy -kalirolling check IPtables version- type that option in terminal with dports option.
This is the quickest way to reproduce.

**Comment by xpz3** [comment] 2019-01-23 14:19
Just take your time. No need to support a specific device. But since there are lot of users trying to make everything work on mobile devices, I thought i could point out an error relating to IPtables.

**Comment by OscarAkaElvis** [comment] 2019-01-23 14:26
Yes, the problem is related to your iptables... but I can tell that iptables v1.8.2 and iptables-legacy v1.8.2 (both of them) support the --dport option. So you have some kind of problem on your iptables that must be fixed. Try to use a clean installed system or something similar. So the problem finally is not related to airgeddon, it seems it is related to your iptables.

On my side I'll try to reproduce it using Kali on LinuxDeploy, will see if able to reproduce it. Now yes again 😄 closing.

**Closed by OscarAkaElvis** 2019-01-23 14:26 UTC
Labels: investigating

**Comment by xpz3** [comment] 2019-01-23 15:01
Yea alright buddy.Check it with your linuxdeploy when you find time. And yes the problem is in no way related to airgeddon. :D

**Comment by xpz3** [comment] 2019-01-24 06:03
Another workaround without touching the source code on Kali-Rolling via LinuxDeploy
1. Install Kali-Rolling via LinuxDeploy
2. Install dependencies for airgeddon
3. apt-get remove iptables
4. change repository to sana(edit /etc/apt/sources.lst and change the repository to http://old.kali.org/kali sana main contrib non-free
5. apt-get update
6. Install iptables with apt-get install iptables
7. Change the repository back to Kali-Rolling
Now the iptables error is gone.

**Comment by OscarAkaElvis** [comment] 2019-01-24 06:34
Awesome, thanks for the tips.

**Comment by xpz3** [comment] 2019-01-24 13:50
I have another problem and didn't want to open another thread as i saw a similar closed issue.  
After launching fake portal and capturing a password, you cannot run another fake portal attack without restarting the chroot container. The services used in the first instance still runs. Hostapd shows error and the webserver says that the port is already in use.

service network-manager restart 
                         Or
service networking restart doesn't solve the issue. I've also tried airmon-ng check kill.
What command can be used to reset all interface and service back to normal so that chroot need not be restarted?
See the screenshot for hostapd
![screenshot_20190124-090226](https://user-images.githubusercontent.com/46419195/51682032-5d635c80-200c-11e9-9b1b-bc9385bb6a1a.png)

another small error msg (doesn't affect functionality) I'd like to notify you.
When you press enter without selecting a network adapter it shows 'expected integer value' or something. But then it prompts to enter the option again so functions fine.

**Comment by OscarAkaElvis** [comment] 2019-01-24 16:17
Sorry, but on a "standard" linux, if that kind of issue is appearing is enough restarting network manager. I can't tell you what to do. In fact, I can't install Kali on Linux Deploy right now. It seems now the download of the images is not free 😢 . Time ago I was able to download images without any restriction but right now is not possible. So it will require more time for me in order to be able to reproduce your stuff.

**Comment by xpz3** [comment] 2019-01-24 19:07
The issue was caused due to hostapd and lighttpd processes running in the background.

Solution
Open terminal and issue two commands
1. kill -9 `pgrep hostapd`
2. kill -9 `pgrep lighttpd`
3. Remove and reinsert the usb otg wifi card.
Now evil twin portal works fine and captures password.
Every time after stopping the evil portal with our without capturing password, the above three steps need to be done or else the chroot need to be restarted.
Maybe its easier to include the above commands in the source code when the evil twin portal was stopped with our without password captured.
It feels good to have all these on my phone that fits in my pocket. lol

**Comment by OscarAkaElvis** [comment] 2019-01-25 08:47
The code after a captive portal attack is doing this:

![image](https://user-images.githubusercontent.com/5803348/51734664-7fe58c00-2085-11e9-93c5-826e9ad0a13f.png)

So it is already killing it and usuallly it is doing it flawlessly without using any special signal so -15 sigterm is enough. It seems for you it is not enough and the kill -9 (sigkill) is needed but this must be because something special for you due some special configuration you have. I can't tell you the reason, it maybe a lot of factors (driver, card, O.S., etc). Anyway it is an external problem, so for the moment we are not going to perform any change on code.

Regarding LinuxDeploy... I'm not able to install a Kali (or any other) image. It seems this last release is not working for me for some reason. Maybe I can try to download an older apk to try again. Maybe one day I'll be able to reproduce your stuff... for now I can't, sorry.

**Comment by xpz3** [comment] 2019-01-25 09:33
No problem for now the workaround is good for me. No need to do anything just for me. 
If you want to support arm devices in future, i can upload a working image of OnePlus3 as we have the same device.
It seems that your LinuxDeploy installation properties is causing the problem. Also you need to allow root permissions for LinuxDeploy to work. As i said earlier, there is no rocket science for setting up LDeploy. Im sure either root permission or configuration of the container or repository address maybe incorrect.

**Comment by xpz3** [comment] 2019-01-25 09:35
Forgot to say that you need to install BusyBox as well

**Comment by OscarAkaElvis** [comment] 2019-01-25 09:58
I know how to do it. I did in the past.... usually it's an easy task, I know all the stuff about busybox and root permissions... I'm just getting errors while LinuxDeploy is trying to create the partitions... it is something related to the new version of Linux Deploy, believe me... I need more time to test (try and error) but now I'm very busy.

P.S. airgeddon is supporting arm devices, it works flawlessly on Raspberry PI. It was tested on Rpi, RPi2 and Rpi3 using Kali, Raspbian and Parrot. It seems the problem is only on this rare scenario. That's the reason I'm trying to configure it for me.... to test.

**Comment by xpz3** [comment] 2019-01-25 10:09
Man dont install it to partitions. Install it as a directory. It works flawlessly.

**Comment by OscarAkaElvis** [comment] 2019-01-25 21:04
I moved forward on this "odyssey". Finally I was able to configure Kali on Linux Deploy. As I said, something is happening with the latest apk. I downloaded a couple of versions before from their github and it worked like a charm.

Ok, now I have Kali installed. After installing tons of packages, airgeddon dependencies, configure vnc and ssh server to connect to it from my computer or even from the phone using a client, etc etc etc... now I have almost all working.

Now I have a new problem. I plug any of my alfa wireless cards (I have three different) to the OTG cable and Kali is not recognizing any of them. I tried connect, reconnect, plug, unplug, reboot Kali, reboot phone, etc... maybe I'm missing something, not sure now. Even the light of any of the Alfa cards is not lighting...

As you can see on this screenshot, I'm close. On the screenshot you can see only the internal card which is not supporting monitor mode (it appears twice as 22 and 23 but is the same card).

![oneplus3kali2](https://user-images.githubusercontent.com/5803348/51772667-e225a780-20ec-11e9-97a9-42d4845dc9b7.png)

Any suggestion? I need more time to get deeper on this... I think my OTG adapter cable is ok. I didn't used it for a long time but it used to work time ago. 😢

**Comment by xpz3** [comment] 2019-01-26 04:52
You need to install usbutils and issue the command lsusb

**Comment by xpz3** [comment] 2019-01-26 05:19
You nee to install usbutils and issue the command lsusb.
If your adapter shows up, then the driver is ok. Or else you need to install a supporting kernel with the driver.
Im using oxygenos 4.0.2 stock rom wit the boeffla kernel fir OnePlus 3 edited by zanezam. 
You could also install the kernel from nethunter wiki for oneplus 3 for OxygenOS, which is also by zanezam. No need to install nethunter. Install only the kernel. So the steps would be
1. Install OxygenOS
2. Install SuperSU version SuperSU-v2.82-201705271822.zip
3. Install kernel - boeffla kernel or oosnethunter4.x.x kernel
4. Install BusyBox
5. Install LinuxDeploy, vnc viewer, ssh client
6. Configure LDeploy for kali and install to a directory if possible rather than a file or partitions.
7. Check lsusb to check for the wireless card.
8. If it shows up but wlan1 is not getting detected, you need to insmod the driver modules. In my case i use 

busybox insmod /system/lib/modules/ath9k_htc.ko
busybox insmod /system/lib/modules/mac80211.ko
9. On every reboot you need to insmod the modules if lsusb shows the wificard but wlan1 not showing automatically
if nothing is working for you i can upload my system.img, boot.ig and data.img. you just need to flash that and everything will ve installed.
Also if you installed a previous version of LinuxDeploy, make sure you are still using the Kali-Rolling repository.
Regarding your partition issue with the latest LinuxDeploy, i think you are using BusyBox by stericson. For partitioning to properly work i think you need to install BusyBox by meefik. I also had the same issue earlier but 2 years back. But niw i dont install it to file or partition and im using install to directory instead, and there is no partitioning.
The benefit of using directory is that you can edit or replace any file from the host android rather than editing inside ssh or vnc. For example, you can edit the sources.lst file using a root browser from android rather than leafpad or vi or nano inside LinuxDeploy.
Im happy to help you with this. 
The wifi card i use is a TP LINK wn722n v1.

**Comment by xpz3** [comment] 2019-01-26 07:42
The insmod should be done on Android terminal emulator or termux and not in LinuxDeploy

**Comment by xpz3** [comment] 2019-01-26 09:49
The official boeffla kernel will not work as it doesn't have the drivers required for monitor mode and injection. There's another modified version from boeffla source with all the drivers but unfortunately the kernel has no support for camera and hence the torch/flashlight wont work. 
Im using nougat 4.0.2 OOS. Both modified boeffla and the one from nethunter for OOS 4.x.x works fine for me.

Im currently using multirom. Latest OOS Oreo OS as primary and this nougat version 4.0.2 OOS as secondary. Camera and everything works in oreo with official kernel and linux tools on secondary rom. 
Here are the links for the modified kernels from boeffa source.
This is for oneplus 3 only and not oneplus 3t
https://m.mediafire.com/folder/z2hcao6kc2lnc
The xda page 
https://forum.xda-developers.com/oneplus-3/oneplus-3--3t-cross-device-development/kernel-boeffla-kernel-linaro-uber-t3455888

The official boeffla wont work. It doesnt have any drivers for monitor mode and injection.

**Comment by xpz3** [comment] 2019-01-26 10:00
Im not using nethunter. Its old and not maintained. You will get all outdated tools since it comes as package. Im using official OOS 4.0.2 with only modified kernel i.e. the kernel built frim boeffla source for oneplus 3.

**Comment by xpz3** [comment] 2019-01-26 10:38
Make sure you flash the version having nethunter in its name.all others WONT WORK. The first link in the media fire is a kernel for nethunter and hence it contains drivers for all usb adapters.
Again if you are confused, you dont need to install nethunter ROM you need to install only the kernel for nethunter which has the drivers.

**Comment by OscarAkaElvis** [comment] 2019-01-26 11:08
Yeah, I see is the same "shit" as time ago. This stuff hasn't evolution. There is no kernel for Oneplus3 supporting all (Nethunter, flashlight, camera).

I'm not going to set dual boot on my phone and I'm not going to change my ROM which works very well, and for sure I need all the standard phone features working (camera, flashlight)... so... maybe I can install temporarily a kernel to make work the usb drivers just for testing and then restore my official kernel. That's all I'll do. Donwloading this kernel you linked...

**Comment by xpz3** [comment] 2019-01-26 11:17
I have compiled a kernel for oreo on oneplus3 but not for oos, it was for lineage. Camera and usb adapters drivers were working well. But i like stock oos and if i could successfully build a kernel for oos with drivers and test it to be stable with all stock features working, ill post a link.

**Comment by OscarAkaElvis** [comment] 2019-01-26 12:46
Checking my old Oneplus stuff I saw that I was fighting on this time ago... I finally found a kernel supporting Nethunter, flashlight and camera.... but there are more problems. As you can see, I made a post on the XDA forum on boeffla's thread one year ago:

https://forum.xda-developers.com/oneplus-3/development/kernel-boeffla-kernel-xx-09-2016-t3455467/page84

On that post, I'm reporting to him that Nethunter, camera and flashlight is working ok but.... Android auto is not working when plugged into the car. This is a stuff a really need because I use it everyday on my car... I remember now this was one of the reasons to remove the kernel and why I abandoned this researching.

If you compile a kernel for oreo on oneplus3 for OOS with usb support, keeping flashlight and camera working, and without breaking Android Auto stuff let me know. I could be very grateful for that. That could be awesome!

Anyway, I'll try as I said in my last post to put temporarily a kernel with usb support just for testing... but I can't remember now how to get back to the original kernel. Not sure if original kernel can be flashed in the same way as we flash the custom kernels or if it is only included with the original ROM and all the "package" must be flashed. Thanks for your support on the Android stuff.

**Comment by xpz3** [comment] 2019-01-26 12:50
To flash the original kernel download the original rom and open with winrar or winzip or any archive manager. Then extract the boot.img from i flash it with twrp. Done
As for android auto, my car doesn't support it so i cant test it. Ill let you know if i succeed.

**Comment by OscarAkaElvis** [comment] 2019-01-26 12:55
Great!

I downloaded the last original rom from oneplus: https://www.oneplus.com/es/support/softwareupgrade/details?code=4

So now I can try and then get back. I'll try to reproduce your problem flashing the custom kernel you suggested before.

Let me know if you succeed compiling that new kernel. That could be awesome. Sadly I have no knowledge about Android stuff and I can't help here... maybe I can help only testing.

**Comment by xpz3** [comment] 2019-01-26 12:56
I must also say that you should try out multirom when you have time. Its working great for me. Stock untouched rom is separated so you wont lose any functionality. Isolate the Linux stuff on a secondary rom. For me its working good. No data loss, freeze etc etc

**Comment by OscarAkaElvis** [comment] 2019-01-26 20:32
Attempt failed... this is the report:

I installed this kernel you suggested: https://www.mediafire.com/file/b4xczg0000j1stv/Boeffla-kernel-3.0-OOS5xx-nethunter-V1-OnePlus3-aa64u541-2019-01-16-115549-anykernel.recovery.zip
After installing it, Nethunter is working ok, flashlight and camera is working ok, but other stuff is not working:
Linux Deploy Kali machine is not detecting the wireless cards... no matter what I plug. lsusb output is empty. Same on Kali nethunter... so if there is no hardware, no matter about driver or insmod stuff... not sure what to do. Ahh I forgot, and the Android Auto stuff is not working. I plug it on the car and it doesn't work... bad business 😞 

Tomorrow I'll try another kernel and I'll perform another try.

**Comment by OscarAkaElvis** [comment] 2019-01-26 21:05
Round 2 failed... I installed this kernel (https://kernel.boeffla.de/oneplus3/boeffla-kernel-oos/oos5xx_download/Stable/) and exactly the same result as the first attempt with the other kernel: camera working, nethunter working, flashlight working, usb cards not detected on linux deploy machine, android auto didn't tested but it doesn't worth the time to test if usbs are not detected on Ldeploy machine.

Searching for more kernels...

**Comment by xpz3** [comment] 2019-01-26 22:58
There is only one kernel for your OOS version. Can you give me your WhatsApp or any other contact method?

**Comment by xpz3** [comment] 2019-01-26 23:09
Also I'd like to know your wireless card chipset. It should be compatible with nethunter to work in LinuxDeploy. You can check the compatibility list
The following chipsets are supported by default in most, if not all, NetHunter kernels:

Atheros

ATH9KHTC (AR9271, AR7010)
Ralink

RT3070
Realtek

RTL8192CU
The following devices are confirmed to be working with a NetHunter build:

TP-Link TL-WN722N
TP-Link TL-WN822N v1 - v3
Alfa Networks AWUS036NEH (recommended by @jcadduono)
Alfa Networks AWUS036NHA
Alfa Networks AWUSO36NH
Panda PAU05 Nano
The following devices are confirmed to be partially working with a NetHunter build:

Alfa Networks AWUS051NH (dual band 5 GHz support may be unreliable)
The following devices are confirmed to NOT be working with a NetHunter build:

TP-Link TL-WN822N v4

**Comment by OscarAkaElvis** [comment] 2019-01-31 13:49
This iptables mess was fixed in v9.01 which was released today.

**Comment by yesimxev** [comment] 2019-12-04 19:30
> Im not using nethunter. Its old and not maintained. You will get all outdated tools since it comes as package. Im using official OOS 4.0.2 with only modified kernel i.e. the kernel built frim boeffla source for oneplus 3.

It is not old, there was a time when it was less supported though. I hope you'd enjoy both anyways! 

Checking the iptables issue here, good solution above. What I had to do: on a clean fresh kali chroot install, downgrading iptables to 1.6 solved the issue, port forwarding was back to normal (we needed for mana-toolkit)

**Comment by xpz3** [comment] 2019-12-04 20:51
For airgeddon you don't need to downgrade iptables as the issue was already fixed on v9.01 by adding support to nft

**Comment by yesimxev** [comment] 2019-12-05 00:03
@xpz3 I've noticed, good job! We have only the workaround for now, as Mana and Mitmf is using iptables too AFAIK

**Comment by Githron** [comment] 2025-01-03 20:51
![Screenshot_2025-01-04-04-19-59-556_com offsec nethunter kex](https://github.com/user-attachments/assets/1eae74f3-a8a9-4b03-94c5-24718391498e)


Help, there is no access portal when I click the fake AP

**Comment by OscarAkaElvis** [comment] 2025-01-03 21:24
It seems you are not using iptables. Seems like the error is for nftables. You can try forcing It in options file setting AIRGEDDON_FORCE_IPTABLES=true

https://github.com/v1s1t0r1sh3r3/airgeddon/wiki/Options

But please, don't hijack old threads. If you have more comments, join to our discord server. Invitation link is on contact section at wiki.
