### ISSUE TITLE
Wps search error

### ISSUE THREAD

**Issue by carlosnewmusic** [v1s1t0r1sh3r3/airgeddon#217] opened 2019-01-15 00:07 UTC
#### What is your airgeddon version?
8.12 deb binary
#### What is your Linux O.S. and which version?

Kali Linux 2018.4

#### Which is the chipset of your wireless card?

Qualcomm Atheros QCA6174 802.11ac

#### Describe the issue and the steps to reproduce it

I select in the first menu wlan0, I give option 2 to put it in monitor mode, I give to option 8 for the wps menu and then to option 4, but it does not show me any network when there are wifi networks with wps activated

![imagen](https://user-images.githubusercontent.com/19379457/51148978-7461bc00-1860-11e9-92bf-814cd7d8fecf.png)

#https://github.com/v1s1t0r1sh3r3/airgeddon/issues/206#issue-394558873

**Comment by carlosnewmusic** [comment] 2019-01-15 01:04
Apart the package does not create an item in the menu, as it should happen when installing the package as a debian package
![imagen](https://user-images.githubusercontent.com/19379457/51151145-e5f23800-1869-11e9-8e6f-ed3733642784.png)

**Comment by OscarAkaElvis** [comment] 2019-01-23 11:17
Closing due lack of information.

**Closed by OscarAkaElvis** 2019-01-23 11:17 UTC
Labels: waiting for info

**Comment by v1s1t0r1sh3r3** [comment] 2019-01-25 18:51
On v9.0 , Kali deb binary package will include the addition of the icon in the menu as shown below:

![imagen](https://user-images.githubusercontent.com/17899365/51766325-8d793100-20da-11e9-9f85-cd5eb32c2294.png)

**Comment by carlosnewmusic** [comment] 2019-02-07 12:52
> It is normal to not be in kali menus. airgeddon is supporting Kali but Kali is not supporting airgeddon. Maybe if in the future Kali decide to add airgeddon to their repositories, it could be done to be present on menus. For now, it doesn't worth the time to do something like that. Anyway, is as simple as execute "airgeddon" command once installed from any path.
> 
> Regarding your problem. It can be related to a driver or external problem. I checked the binary deb package on kali and is working fine for me.
> 
> I'll do a wild guess of your problem... Is your Kali a Virtualbox machine and are you using a Ralink chipset card? This behavior is a typical problem of this scenario.
> 
> You should get no problems using ralink + Vmware, but using Virtualbox, there is some kind of incompatibility with Ralink chipset cards and Virtualbox due something related to usb speed. If your computer is old it should work. If your computer is new (usb3), you can experience this problem (scanning and nothing appearing). It is not related to wps. You should get same result doing a non-wps scan... no networks appearing.
> 
> If I hit of your scenario (ralink + virtualbox) I have a workaround for you. I'll explain it (maybe it could be also useful to others). Nothing you can do on Vbox configuration (I tried modifying usb speed but it didn't worked). But pluging a usb 2.0 usb hub and then plugging the wifi card to the usb hub. Doing this it should work!
> 
> Good luck!

I'm from a laptop with the Wi-Fi interface specified above, but if the notebook has USB 3.0 ports

**Comment by JBalanza** [comment] 2019-02-07 13:11
I'm thinking about two possible solutions to this:
- Try installing all possible drivers in your host. Even that, if you're using windows 7 or older you could have interoperability problems. Try updating your host to Windows10 y you haven't done it yet. (This helped me a lot with Atheros and Ralink chipsets recognition in VirtualBox).
- Try using aircrack-ng commands in order to discover if the problem is in airgeddon or in the base tool. Try the following: `airmon-ng start wlan0` and then `aircrack-ng wlan0mon`

Regards.

**Comment by carlosnewmusic** [comment] 2019-02-07 13:36
>     * aircrack-ng wlan0mon

![captura de pantalla_2019-02-07_13-54-20](https://user-images.githubusercontent.com/19379457/52414823-9f4cd200-2ae5-11e9-8e78-64e94fd385a2.png)

**Comment by JBalanza** [comment] 2019-02-07 13:40
I apologize, The second command you shuld run after  `airmon-ng start wlan0` is `airodump-ng wlan0mon`.

**Comment by carlosnewmusic** [comment] 2019-02-07 16:43
> airodump-ng wlan0mon
it stays that way, like in the script
![captura de pantalla_2019-02-07_13-54-20](https://user-images.githubusercontent.com/19379457/52427187-c87a5c00-2aff-11e9-8ead-fa9e61337b21.png)

**Comment by JBalanza** [comment] 2019-02-07 18:37
As I see, the problem is in your kali or your window's hosted VM setup. Im sorry to say that there is nothing airgeddon can do for you to help solve your problem because the problem is not oiriginated by argeddon. I can last recommend you something but I need to know the following:
- Are you using Windows to host your Kali VM. In that case what Windows version and VM Manager are you using (Virtual Box, VMWare...etc)?.
- In case you are not hosting the Kali VM and you are running directly the Kali OS, The Wifi card specified is an internal one or it is an external one (plugged by USB)?.

**Comment by Staylejkxd** [comment] 2020-03-14 22:01
Hello, i'm sorry for re-opening this, i have the same issue like @Carlosnewmusic and i followed the suggestion given by @JBalanza and  the "airodump-ng wlan0mon" gave me results.
If someone can help me, i'm stuck and i dont find any solution for this. :/

**Comment by Khandkar-Sajiduzzaman** [comment] 2024-08-13 20:51
![Screenshot 2024-08-14 025109](https://github.com/user-attachments/assets/142947fe-05cf-440b-b445-27808b520812)


Hello everyone, I am also facing the same problem. 

1. What is my setup?
- Kali + VM

2. My wifi Adapter??
- Tp-Link T2U  [Chipset: RTL8812AU]

3. Are my drivers updated??
- yes to the latest version

4. My RTL8812AU driver??

-  yes using [ apt install realtek-rtl88xxau-dkms ]  command

**Comment by OscarAkaElvis** [comment] 2024-08-13 21:12
omg... @Khandkar-Sajiduzzaman , that's the intended behaviour... you should stop the scan. Otherwise it is not stopping by itself. It is designed that way 🤦 . And please... don't spam on old github issues. Join discord to ask questions.
