### ISSUE TITLE
Need support for rtl8812au drivers

### ISSUE THREAD

**Issue by kimocoder** [v1s1t0r1sh3r3/airgeddon#203] opened 2018-12-22 21:00 UTC
airgeddon needs support for the rtl8812au drivers, since the drivers doesn't support "virtual Interface".

Other tools added support for it, like the wifite2 and airmon-ng also got support now.
This commit [here](https://github.com/derv82/wifite2/commit/c7a952b3dfc49150760a521388c1634ccc1ac88b) added support for the drivers at wifite2

**Comment by OscarAkaElvis** [comment] 2018-12-23 10:45
This topic is a little bit recurrent. It is duplicated. It was discussed more times here:
https://github.com/v1s1t0r1sh3r3/airgeddon/issues/185
https://github.com/v1s1t0r1sh3r3/airgeddon/issues/100

airgeddon is using mainly airmon to set monitor mode, so if airmon now supports it, great, it will work in airgeddon to set monitor mode. So airgeddon doesn't need to support anything regarding the mode setting. In fact, since v8.11 other cards can be used in airgeddon, not only airmon compatible cards, so it can be used. I used this card with airgeddon and it worked to set it on monitor mode and to capture handshakes, etc. Other story is to use Evil Twin attacks which are using hostapd. Hostapd has problems with this card but I know some people installing a different driver solved it, so it is not related to airgeddon itself. 

You didn't respected the issue policy creation. Closing.

**Closed by OscarAkaElvis** 2018-12-23 10:45 UTC

**Comment by OscarAkaElvis** [comment] 2019-11-11 21:20
Ding ding ding!!! your dreams come true: https://github.com/OscarAkaElvis/airgeddon_realtek_chipset_fixer

**Comment by Medullitus** [comment] 2022-02-04 17:02
> Ding ding ding!!! your dreams come true: https://github.com/OscarAkaElvis/airgeddon_realtek_chipset_fixer

Link is not working? Can you re-upload it please?!

**Comment by OscarAkaElvis** [comment] 2022-02-04 21:15
The new link is this: https://github.com/OscarAkaElvis/airgeddon-plugins

Now the repo has more plugins.

Anyway, if you read the README, that plugin was designed specifically for airgeddon v10.0, then on v10.01 or higher the plugin code was included directly in the main code of airgeddon. So the plugin is not needed anymore. Thanks to that, you can use awful chipsets partially in airgeddon. Instead of having nothing working, now at least you can switch mode, capture handshakes and other basic operations... but the fact of that is a shitty chipset didn't change. It doesn't support VIF (virtual interface) due to hardware reasons... so is not anymore we can do. Check the list of nice cards to buy instead of that!

https://github.com/v1s1t0r1sh3r3/airgeddon/wiki/Cards%20and%20Chipsets

**Comment by xxxcrow** [comment] 2023-09-19 17:15
@OscarAkaElvis don't see about what exactly you said "shitty chipset"
But mine adapter is AWUS036ACM, does it relate to me
I'm getting the "no VIF support" error

**Comment by OscarAkaElvis** [comment] 2023-09-19 17:28
Not sure why are you writing on an old issue which is not related to your card or chipset. Please, don't do that. It's better to read the wiki carefully first. You'll find that your card has a nice chipset (MediaTek MT7612U) which is ok for wifi hacking as you can see here: https://github.com/v1s1t0r1sh3r3/airgeddon/wiki/Cards%20and%20Chipsets

If you are getting a "no vif error" as you are saying maybe you don't have selected the right card or maybe you don't have the card or the chipset you think you have, a good way to check it, is to launch `airmon-ng --verbose` command on linux console. It will show your chipset.

If you are curious about what is VIF, you can find out it here: https://github.com/v1s1t0r1sh3r3/airgeddon/wiki/FAQ%20&%20Troubleshooting#what-is-vif

Please, if you have more questions join to our discord server. Invitation link is on contact section at wiki.

**Comment by xxxcrow** [comment] 2023-09-20 03:28
@OscarAkaElvis oh, it seems mine is actually awus360ac with a different chipset 🫡
