### ISSUE TITLE
evil twin attack does not start

### ISSUE THREAD

**Issue by CyberTheReape** [v1s1t0r1sh3r3/airgeddon#201] opened 2018-12-14 18:18 UTC
hello bro.. i have any problem .. i did buy new wifi adapter... tenda u12 ac1300... it is using RTL8812AU chipset... i installed wifi driver. Now it is working in kali linux. I switch to monitor mode before launching airgeddon...but wlan0mon does not write when I check with the ifconfig command ..

same this video goes into monitor mode but it says wlan0 ... please watch this video
https://www.youtube.com/watch?v=zZG65GkWGdU

I'm running the airgeddon program...I choose the wifi adapter and I'm launching the deauth attack for the evil twin attack...I catch handshake after the attack is over...now I  launching an evil twin attack with handshake...opens new terminals on the screen..evil twin attack opens 6 new terminal on display..

now my problem starts here ...no attack occurs at opened terminals...deauth not attacking..no progress in other terminal windows..only terminals open but not attacking...

deauth attack terminal says "mon: failed"   ...... Could this be because the problem is not wlan0mon?
I said that it appeared to be wlan0 when the wifi adapter entered monitor mode...Do you think this might be the cause of the error?

then I closed the airgeddon program..i did reboot the computer and reboot the airgeddon program..this time I didn't put my wifi adapter into monitor mode before..After I started airgeddon, I switched my wifi adapter to monitor mode...

I did the deauth attack again ..I caught handshake again ...I started the evil twin attack ... new terminals opened again but the attack did not start... tenda u12 wifi adapter supporting injection...

can I change the wlan0 wifi adapter name to wlan0mon in monitor mode? How to change wlan0 name as wlan0mon ???

please help me... what is problem ??

**Comment by v1s1t0r1sh3r3** [comment] 2018-12-14 21:46
Hello. I think your problem is related to the driver you are using. That adapter is always problematic.

Don't worry about the name of the adapter. It doesn't care if it is named wlan0 or wlan0mon. Usually airmon is setting it as wlan0mon when it is set in monitor mode, but your adapted is not supported by airmon so that's the reason to be in monitor mode as same name wlan0, because the technique used to set it to monitor is just the `ifconfig wlan0 down && ifconfig wlan0 mode monitor && ifconfig wlan0 up` technique.

The problem is not related to airgeddon but I can try to help you anyway. I can recommend to you a couple of things. First try to use for the driver the package available on apt. It is called "realtek-rtl88xxau-dkms". As you can see on this similar issue opened, it worked for somebody: https://github.com/v1s1t0r1sh3r3/airgeddon/issues/100

Then, you can check this thread: https://github.com/aircrack-ng/rtl8812au/issues/93

There, some aircrack developer was talking about to include that adapter to be compatible to airmon. Even there are a couple of commits referenced on which it is included. Maybe you can use a newer version of aircrack suite in order to let airmon to handle your monitor mode, sorry, not sure about what version of aircrack you need for this. Maybe you need to add some beta or experimental version from some branch. Not sure if this is going to help you, but it would be nice to try.

If that is not working for you, I think here is a user that maybe can help you about this and maybe he can recommend a custom driver to be used for this adapter, can you share the link @jarilaos ?? thanks.

**Comment by evilginx** [comment] 2018-12-14 22:35
Thanks for answer... i did install driver with this method (realtek-rtl88xxau-dkms)

İ did look realtek office web page for rtl8812au driver... but realtek not supporting driver for linux...

Now i am thinking. İs realtek idiot ?  Or we are idiot? If a chipset firm has not made a driver for linux, how is it reasonable to buy the wifi adapter using this chipset?

realtek firm rtl8812au are not smart enough to code open source codes?

realtek company knows that this product will not work well in linux

realtek knows that it can not get 5ghz power in linux with this product

My new wifi adapter (tenda u12 ac 1300)

İ have old wifi adapter.. 

İt is using ahteros chipset. İt is not supporting injection.

But it is supporting monitor mode and brute force attack.
(Tplink-wn321g)

Today i tested tenda and tplink

Tenda seeing 4 wifi network 
Tplink seeing 6 wifi network

I want to ask you a question now.
tomorrow I'm thinking to return the tenda u12 wifi adapter..
but I am undecided.Do you think I should return this product?

**Comment by v1s1t0r1sh3r3** [comment] 2018-12-15 06:30
Yeah, Realtek is not supporting it for Linux. That's the reason because I say that this card is always a problematic card. I don't like it.

I can't tell you what you must buy or if you should return it to the store where you bought it, but in my opinion, to get everything easier, I'd choose an adapter with drivers supported by vendor, compatible to airmon (this makes life easier), compatible to hostapd, supporting injection and with 5ghz if possible.

**Comment by jarilaos** [comment] 2018-12-16 12:14
Hi, I have this wifi adapter: [Alfa AWUS036ACH](https://www.amazon.es/Alfa-AWUS036ACH-Adaptador-Dual-AC1200/dp/B00VEEBOPG), which is not compatible with airmon yet, but @v1s1t0r1sh3r3 managed to fix it.

Evil twin attack and all the other features of airgeddon work for me with this official repository branch: [v5.2.20](https://github.com/aircrack-ng/rtl8812au/tree/v5.2.20)

I recommend installing the github repository instead of with apt. Maybe, you will have to try different branches. Don't forget to install the dependencies and run `airmon-ng check kill` before start monitoring.

I think my adapter is not the best choice yet (expensive and in development), but the repository is being updated and the developer works hard to fix it.

**Comment by evilginx** [comment] 2018-12-16 13:02
İ did send back my wifi adapter... i know it is working with brute force.... bu i have other wifi adapter. İt is working with airmon-ng.. but i can not do evil twin attack. For it i did buy new adapter. İ want to do evil twin attack.. i cant do it with rtl8812au... i did send back my wifi adapter.... i will buy new adapter. But i think best wifi chifset is ahteros for wifi hacking...

**Comment by v1s1t0r1sh3r3** [comment] 2018-12-16 13:41
yeah, atheros is awesome but i think there is no atheros for 5ghz.

Anyway, closing this. Feel free to comment here anything related to this chipset stuff. Regards.

**Closed by v1s1t0r1sh3r3** 2018-12-16 13:41 UTC
Labels: question
