### ISSUE TITLE
Hostapd shows not being installed, even though it is

### ISSUE THREAD

**Issue by mattyount28** [v1s1t0r1sh3r3/airgeddon#309] opened 2019-10-05 01:31 UTC
#### What is your airgeddon version?

v9.23

#### What is your Linux O.S. and which version?

Kali Linux 2019.3

#### Which is the chipset of your wireless card?

I am on a usb boot, so my wlan chipset shows as unknown. 

#### Describe the issue and the steps to reproduce it

Trying to go into evil twin attack, it says I need hostapd. So, I open up a new terminal and type `apt-get install hostapd`, but even after that (and updating, I also tried different methods of installing hostapd, still didn't work) it still says that I need to install hostapd. When I go to install hostapd, it says that it is already on the latest version, which is 2:2.9-1. Thanks :)

**Comment by OscarAkaElvis** [comment] 2019-10-05 07:10
Pretty weird man. Sorry but I'm not able to reproduce this issue. I also have lastest Kali in a VM and hostapd is easy to install by apt. Please, launch these commands:

`hostapd -v`
`which hostapd`
`dpkg -l | grep hostapd`

You should see something like:

![image](https://user-images.githubusercontent.com/5803348/66251198-ced3dd00-e74d-11e9-842e-375afaddb0a5.png)

Did you launched `apt update` before `apt install hostapd` ??? What is the output of apt? Is it saying that it is installed correctly? please, put a screenshot here.

Maybe your problem is related to your PATH environment variable. Maybe it is installed but airgeddon is not able to locate the binary. Usually hostapd is installed at `/usr/sbin/hostapd` as you saw in my screenshot as a result of which command. Check your PATH var and be sure that dir is there.

In any case this is not related direcly to airgeddon development and there is nothing we can do in the script to fix your problem. I mean, it seems more a O.S. problem than an airgeddon problem. You must achieve to be able to execute a `hostapd` command from anywhere in your Kali. Due this, I'm going to close this issue. Anyway you can keep posting here and we'll try to help but as I said,

**Closed by OscarAkaElvis** 2019-10-05 07:10 UTC
