### ISSUE TITLE
Captive portal is not redirect to login page.

### ISSUE THREAD

**Issue by seksitha** [v1s1t0r1sh3r3/airgeddon#171] opened 2018-08-27 03:41 UTC
#### What is your airgeddon version?

8.11
#### What is your Linux O.S. and which version?

kali 2018.2
#### Which is the chipset of your wireless card?

Atheros AR928X
#### Describe the issue and the steps to reproduce it

Captive portal is not redirect to login page. All working well but client did not see the password login page.

**Comment by OscarAkaElvis** [comment] 2018-08-27 10:02
Sorry but it is working for us. Provide more details in order to be able to reproduce the problem.

Which operating system has the client? which is the browser used by the client?

Bear in mind that Captive portal Evil Twin attack is not modified since a lot of versions ago and it's fully working so the most probably thing is some kind of problem on the client side or in the browser. Maybe the client has not javascript enabled or that kind of stuff.

**Comment by seksitha** [comment] 2018-08-27 14:07
Hi, the client run on Windows 7. browser firefox/ chrome. when the client open the browser and type url, it is not even redirect to captive page if it is https but http is redirected. for osx or ios, the dialog box page is automatically populated.

**Comment by OscarAkaElvis** [comment] 2018-08-27 14:49
Ok but that is the intended way. Everything is working fine.

https is not supported because we don't have a legitimate certificate to put on captive portal. A certificate print "as green" by a browser cost money. We can issue a self-signed certificate but we really prefer to show "nothing" instead of show a warning because of the certificate. That behavior will make the victim to suspect. It's better to wait until he or she to put a http url.

Somebody suggested to use LetsEncrypt certificates but the free certificates expire on 90 days and is something that we are not going to maintain (changing it every 90 days).

Closing.

**Closed by OscarAkaElvis** 2018-08-27 14:49 UTC
Labels: waiting for info
