### ISSUE TITLE
The fake network does not appear to be hacked I have tried on more than one operating system

### ISSUE THREAD

**Issue by mohamedmzeka1** [v1s1t0r1sh3r3/airgeddon#418] opened 2021-01-21 17:02 UTC
#### Describe the issue and the steps to reproduce it

![Uploading Screenshot at 2021-01-21 05-02-14.png…]()

My problem is that the fake network does not appear to be hacked

**Comment by cjb900** [comment] 2021-01-21 17:36
Well there are several things wrong with the information you provided. 

The latest version of airgeddon is 10.40. So if you are running 10.21 i would update to the latest version

The OS's you mentioned. Parrot OS 2020 and Kali Linux 2020 are not actual version of these OS's. So its hard to tell what version you are actually running. The latest version of Parrot OS is 4.10 and the latest version of Kali Linux is 2020.4. 

the chipset you provided "IEEE 802.11n" is not an actual chipset but just the wireless networking standard of what ever chipset of the adapter you are using. 

The picture you provided just links back to this post and does not take you to an actual picture.  

I don't think you understand what airgeddon is or does. If you are performing an evil twin attack this is a type social engineer attack where we deauth any wireless devices connected to a network. Once a devices is disconnected the victim has to realize their device was disconnected. Once they realize this we hope they try to reconnect to their real network and see that they can't. We then hope that they see the fake network airgeddon creates with the same name as their real network. Once they connect to the fake network we then hope they get the captive portal page prompting them for the password of their network. Once they enter that airgeddon captures that so we then know the password of their network. So airgeddon does not automatically hack the victim network and make it available to use with out the password and there is no tool i know of that can do that.

**Comment by OscarAkaElvis** [comment] 2021-01-21 17:38
I saw you tried to upload a screenshot but for some reason it is not uploaded, so we can't see anything. Please, upload it again. Otherwise is hard to help you.

Anyway, I must say reading the title of your "issue" that are trying to hack the fake network... ¿? airgeddon has a lot of features... not sure what you are trying to perform. Let's suppose that you are trying to perform an Evil Twin attack which is creating a fake network... that network is yours... is no the network to be hacked.... I think you don't understand the concepts. @cjb900 tried to explain to you on his post. Read it carefully and if you have doubts, connect to our discord channel to keep talking. You can find the public invication link to join at our wiki on contact section.

**Comment by mohamedmzeka1** [comment] 2021-01-21 18:08
![Screenshot at 2021-01-20 15-45-40](https://user-images.githubusercontent.com/76184211/105392833-546deb80-5c24-11eb-90d3-83a508935ad4.png)
![Screenshot at 2021-01-20 15-45-40](https://user-images.githubusercontent.com/76184211/105392838-559f1880-5c24-11eb-80d4-42c1cf8339d6.png)
![Screenshot at 2021-01-21 05-02-14](https://user-images.githubusercontent.com/76184211/105392868-5df75380-5c24-11eb-93f9-df75dd632d7f.png)

**Comment by cjb900** [comment] 2021-01-21 18:14
So looking at the AP window it shows AP-Disabled. This can be one of 2 things. the chipset in the card you are using is not properly supported or that Parrot OS it is not using the wlanxx naming for the wireless interface. You can find supported cards/chipsets here https://github.com/v1s1t0r1sh3r3/airgeddon/wiki/Cards%20and%20Chipsets and information on how to change the wireless interface here https://github.com/v1s1t0r1sh3r3/airgeddon/wiki/Cards%20and%20Chipsets

**Comment by OscarAkaElvis** [comment] 2021-01-21 18:19
Yeah, as @cjb900 said, you should change the interface name from the ugly new name to the old style following that link instructions: https://github.com/v1s1t0r1sh3r3/airgeddon/wiki/Consistent%20Network%20Device%20Naming

Then another recommended thing to do if you are suffering this kind of problems is to perform this command before launching airgeddon: `sudo airmon-ng check kill`

I insist, if it is not a bug of airgeddon (and it is not clearly, this is just an user asking for support) is better to give you support in Discord channel... real time conversation, more people helping. If you are so lazy to search for the link to join, here it is: https://discord.gg/sQ9dgt9

Closing

**Closed by OscarAkaElvis** 2021-01-21 18:19 UTC
Labels: waiting for info

**Comment by mohamedmzeka1** [comment] 2021-01-21 18:23
Thanks for attention, I have made sure that the Wi-Fi receiver is supported, but the problem has not been resolved. Can I contact you personally? Please give me your WhatsApp number

**Comment by OscarAkaElvis** [comment] 2021-01-21 18:26
Whatsapp number? 🤣  looool... yeah I usually tell my phone to strangers.... 

Please, be serious. Follow the instructions we told you and try. If still is not working for you, connect to discord channel. We created it precisely for this kind of things.

**Comment by mohamedmzeka1** [comment] 2021-01-21 18:28
Yes, the name of the cat is as you say, but I do not have that experience to change his name. It is difficult to follow the steps that I said. How weak I can speak English. I hope you give me a way to communicate with you and I can follow your instructions and thank you

**Comment by cjb900** [comment] 2021-01-21 18:29
we did give you a way to communicate with us. If you are unable to follow the steps we previously gave or contact us on discord we can't help much further.

**Comment by OscarAkaElvis** [comment] 2021-01-21 18:30
Yes, we are giving to you instructions on wiki, very detailed. We are also giving to you a way to communicate, the discord channel... so go to https://discord.com/ , register and account and join to the channel clicking on the mail we already put here to receive help.

**Comment by mohamedmzeka1** [comment] 2021-01-21 18:30
Sorry for asking for the phone number, I do not know the rules here. This is the first time I am sharing a problem. I can give you my number if you want to make things easier for me or you can give me a video and I will solve the problem

**Comment by OscarAkaElvis** [comment] 2021-01-21 18:31
I think you have here posted all what you need to fix it or to contact us on the channel. Locking.
