### ISSUE TITLE
Eviltwin deauth problem

### ISSUE THREAD

**Issue by padranina** [v1s1t0r1sh3r3/airgeddon#604] opened 2024-07-31 18:08 UTC
what is your airgeddon version?
Latest

What is your Linux O.S. and which version?
Kali latest

Is your O.S. running in native mode or is a virtualized system? in that case, VMware? VirtualBox? Other?
Dual boot with windows 10

Which is the chipset of your wireless card?
I don't know. Laptop: asus b1500cepe

Describe the issue and the steps to reproduce it
When I attack evil twin captive portal works but it doesn't disconnect connected devices, as a result nobody falls for this trick.
Note : I used all death method and restarted laptop several time but deauth when Eviltwin doesn't works. Note:Death works when I don't use Eviltwin.
(Same error happens with fluxion)

**Comment by OscarAkaElvis** [comment] 2024-08-01 08:15
Hi, knowing the chipset of your wireless network card is crucial because the behavior will vary significantly depending on the chipset. Using the right chipset, everything should work smoothly. However, issues like the one you describe are usually caused by using a chipset that is not suitable for WiFi hacking.

Based on what you describe "works when I don't use EvilTwin", sounds like your card supports monitor mode but it is not supporting VIF. To understand what is this, please read this: https://github.com/v1s1t0r1sh3r3/airgeddon/wiki/FAQ%20&%20Troubleshooting#what-is-vif

So, it sounds like you need a proper wifi adapter using a good chipset to work. You can check here the whitelist of the recommended cards and chipsets where even you can find some direct links to buy if you are "lazy" to search: 
https://github.com/v1s1t0r1sh3r3/airgeddon/wiki/Cards%20and%20Chipsets

As you can see, everything is on the Wiki. there are other interesting answers on the FAQ section. So I encourage you to read them to know more about how this works.

You can also join to our Discord server. There you can continue asking if you have more questions. You can find the invitation link here: https://github.com/v1s1t0r1sh3r3/airgeddon/wiki/Contact

Closing.

**Closed by OscarAkaElvis** 2024-08-01 08:15 UTC

**Comment by padranina** [comment] 2024-08-01 08:37
Thanks for help.

**Comment by padranina** [comment] 2024-08-01 08:41
> Hi, knowing the chipset of your wireless network card is crucial because the behavior will vary significantly depending on the chipset. Using the right chipset, everything should work smoothly. However, issues like the one you describe are usually caused by using a chipset that is not suitable for WiFi hacking.
> 
> Based on what you describe "works when I don't use EvilTwin", sounds like your card supports monitor mode but it is not supporting VIF. To understand what is this, please read this: https://github.com/v1s1t0r1sh3r3/airgeddon/wiki/FAQ%20&%20Troubleshooting#what-is-vif
> 
> So, it sounds like you need a proper wifi adapter using a good chipset to work. You can check here the whitelist of the recommended cards and chipsets where even you can find some direct links to buy if you are "lazy" to search: https://github.com/v1s1t0r1sh3r3/airgeddon/wiki/Cards%20and%20Chipsets
> 
> As you can see, everything is on the Wiki. there are other interesting answers on the FAQ section. So I encourage you to read them to know more about how this works.
> 
> You can also join to our Discord server. There you can continue asking if you have more questions. You can find the invitation link here: https://github.com/v1s1t0r1sh3r3/airgeddon/wiki/Contact
> 
> Closing.

Sir just an idea, There is a microcontroller esp32 which can deauth any wifi without connecting(password ) why don't you integrate it and make work simple for airgeddon🙂
https://github.com/risinek/esp32-wifi-penetration-tool

**Comment by OscarAkaElvis** [comment] 2024-08-01 08:50
Esp32 is a piece of hardware... airgeddon is made for linux and it's software. While on linux is possible to attach standard wireless interfaces, there is no need to use any special motherboards like Esp32. Actually, the features mentioned in the link you provided (DoS, Handshake, PMKID, etc) are features already provided by airgeddon. This is completely pointless

Please, stop sharing random ideas here on Github issues. Last warning before banning your account from our Github repo. Sorry but for this kind of discussion we have the proper channel which is the Discord server.

**Comment by padranina** [comment] 2024-08-01 08:56
Ok

**Comment by padranina** [comment] 2024-08-04 15:43
Fuck ur attitude bro

**Comment by v1s1t0r1sh3r3** [comment] 2024-08-04 19:03
Comment deleted and user banned.
