### ISSUE TITLE
Problem during cloning

### ISSUE THREAD

**Issue by c7berFr0g** [v1s1t0r1sh3r3/airgeddon#613] opened 2024-08-27 19:07 UTC
![Screenshot_2024-08-27_22-03-38](https://github.com/user-attachments/assets/2e87cbe7-f69e-4c45-bd0a-452f497bad74)

**Comment by OscarAkaElvis** [comment] 2024-08-27 19:21
You really think this is a problem of the tool to open an issue on GitHub? it is just issues on your side. You didn't even filled out the required fields with the required data to try to help you.

I think you need to google a little bit before opening this damn absurd issues. Closing.

**Closed by OscarAkaElvis** 2024-08-27 19:21 UTC

**Comment by c7berFr0g** [comment] 2024-08-27 19:42
You need to rehabilitate your moral values

**Comment by c7berFr0g** [comment] 2024-08-27 19:53
@OscarAkaElvis
My side is clean and I looked before I brought up the problem here, but your side is devoid of respectful behavior

**Comment by OscarAkaElvis** [comment] 2024-08-27 19:59
What's truly disrespectful is opening an issue on GitHub when the problem isn’t related to the tool, just because you’re facing an issue on your side. This forces administrators and contributors to spend their time reading something over which we have absolutely no control - first, because it has nothing to do with the tool. Your problem would happen with any GitHub repository. Are you going to open an issue in all of them? How many are there? Thousands? Millions? I’m sure you haven’t even bothered to try cloning another repository to verify what I’m saying; otherwise, you would see that the problem isn’t related to this tool.

Second, you didn’t even take the time to read the template that appears when creating an issue on GitHub, where certain information is requested. This leads to an issue creation policy violation, which, as we've clearly stated, will result in the issue being closed directly if it doesn’t comply with the policy.

So, wasting so many people's time, that’s what’s truly disrespectful.

I think you need start googling, or looking for git support or Linux support or something like that. But airgeddon's GitHub issues are used for stuff related to the tool. Locking.
