### ISSUE TITLE
multiple bugs 

### ISSUE THREAD

**Issue by carlosnewmusic** [v1s1t0r1sh3r3/airgeddon#68] opened 2017-03-21 03:19 UTC
#### What is your airgeddon version?
6.11
*Insert answer here*
When I start the scan with wash gives error, 
and I would like to support optirun to decrypt WPA / WPA2 offline,
Erroneous coding of some words
![image](https://cloud.githubusercontent.com/assets/19379457/24131011/61a196f6-0dec-11e7-8ab2-3a3a24e3147e.png)

#### What is your Linux O.S. and which version?
Debian 9 kernel v4.9

#### Which is the chipset of your wireless card?
ath10k_pci and isl3887usb
*Insert answer here if apply*
soporte en modo monitor para ath10k_pci 

ath10k_pci support monitor mode?

#### Describe the issue and the steps to reproduce it
Selecciono la interfaz la pongo en modo monitor le doy a la opcion WPS y a la opcion de scaneo y me reporta error inesperado, hay que primero explorar desde otra funcion para que no de error al iniciar wash solo que al iniciar no devuelve nada

I select the interface I put in monitor mode I give the option WPS and the option of scanning and I report unexpected error, You have to first explore from another function so that it does not error when starting wash only that when starting does not return anything
![image](https://cloud.githubusercontent.com/assets/19379457/24131605/effdb062-0def-11e7-972a-1d7fd031670e.png)

**Comment by kcdtv** [comment] 2017-03-21 09:01
1) Can you paste here  the stdout of `sudo airmon-ng` to know the exact chipset? 
(ath10k is a driver, not a wifi chipset)
There are indeed some compatibility problems with mode monitor and injection with some of the chipsets that use ath10k 
  2) Once mode monitor is enabled on the interface could you please copy and paste the results of an  injection test:
`sudo aireplay-ng -9 wlan0mon`
Thanks.

**Comment by v1s1t0r1sh3r3** [comment] 2017-03-21 20:23
Yeah, waiting for data. As kcdtv said, it seems is a driver problem. Not sure yet but maybe is not related to airgeddon.

Regarding the strange chars... use utf8!!! is showing to you strange chars on spanish special accent chars. Is because your O.S. encoding is not UTF-8. I guess you are spanish (or spanish speaker)... probably you are using es_ES.ISO-8859-1 or any other similar. Change your locale to es_ES.UTF-8 and please, everything here in english. Thank you! 😃

**Comment by v1s1t0r1sh3r3** [comment] 2017-03-31 08:30
Time exceded without any new. Closing.

**Closed by v1s1t0r1sh3r3** 2017-03-31 08:30 UTC
Labels: waiting for info

**Comment by carlosnewmusic** [comment] 2017-04-21 01:11
@kcdtv 
![captura2](https://cloud.githubusercontent.com/assets/19379457/25258018/a09183cc-263c-11e7-8ff4-748c1f708ebf.png)
![captura de pantalla_2017-04-09_01-17-44](https://cloud.githubusercontent.com/assets/19379457/25258019/a0b13640-263c-11e7-8ed5-73d895f99925.png)

@v1s1t0r1sh3r3 How do I do that? and forgive that I have been on exams

**Comment by v1s1t0r1sh3r3** [comment] 2017-04-21 07:07
Are you talking about encoding? That isn't an airgeddon issue. You must solve it on your side using UTF8. Change the locales of your Debian.

Because you are spanish speaker I'll recommend to you a link which is in spanish for your encoding problem: https://miguelmenendez.pro/es/articulos/cambiar-idioma-idiomas-disponibles-sistema-basado-debian.html

But please, don't talk here anymore about encoding, is out of scope.

Regarding your wash scanning problem... not sure to understand. I'll try to describe your problem and in steps and tell me if this is ok to reproduce the problem:

1. Open airgeddon
2. Put your card on monitor mode
3. Perform a wash scannig it shows nothing.
4. Perform a standard scan with airodump in other sub-menu different than wps menu and it shows results.
5. Perform again a wash scan and it show you results

Is this correct for you? If not, explain exactly what is happening.

**Comment by v1s1t0r1sh3r3** [comment] 2017-05-02 13:11
No new info here. Locking.
