### ISSUE TITLE
dnsmasq: config error is REFUSED (EDE: not ready)

### ISSUE THREAD

**Issue by Casper-88** [v1s1t0r1sh3r3/airgeddon#480] opened 2022-03-11 13:46 UTC
#### What is your airgeddon version?
<v11.0>

#### What is your Linux O.S. and which version?
<kali linux 2022.1>

#### Which is the chipset of your wireless card?
MT7610U

Dear Mr/Miss,
How to fix dnsmasq: config error is REFUSED (EDE: not ready)
My dnsmasq is version 2.86

**Comment by OscarAkaElvis** [comment] 2022-03-11 13:47
I tested it with dnsmasq 2.85... let me test on dnsmasq 2.86 to see what happens...

**Comment by Casper-88** [comment] 2022-03-11 13:50
> I tested it with dnsmasq 2.85... let me test on dnsmasq 2.86 to see what happens...

I update to last version. sudo update && upgrade.

**Comment by OscarAkaElvis** [comment] 2022-03-11 14:08
Hmmm... it works for me on BlackArch. You can see the dnsmasq version (2.86).

I copied the generated by airgeddon dnsmasq config file and launched same command that airgeddon is launching... just modified the file to set my ethernet interface (this test can be done even without a wireless card), and launched `dnsmasq -C <config_file>`, and it seems it works... no errors... 

![image](https://user-images.githubusercontent.com/5803348/157883145-c443394c-711d-48f8-a05a-8720102eb999.png)

When I've read the issue I thought "maybe there are some changes on this new dnsmasq 2.86 which could make config to crash", but after this test I don't think so...

Let me more time to investigate or to install a Kali vm to test in the same O.S. as you. I'll try also to do it with wireless card during an Evil Twin attack to try to reproduce it.

Keep in touch.

**Comment by Casper-88** [comment] 2022-03-11 14:15
> Hmmm... it works for me on BlackArch. You can see the dnsmasq version (2.86).
> 
> I copied the generated by airgeddon dnsmasq config file and launched same command that airgeddon is launching... just modified the file to set my ethernet interface (this test can be done even without a wireless card), and launched `dnsmasq -C <config_file>`, and it seems it works... no errors...
> 
> ![image](https://user-images.githubusercontent.com/5803348/157883145-c443394c-711d-48f8-a05a-8720102eb999.png)
> 
> When I've read the issue I thought "maybe there are some changes on this new dnsmasq 2.86 which could make config to crash", but after this test I don't think so...
> 
> Let me more time to investigate or to install a Kali vm to test in the same O.S. as you. I'll try also to do it with wireless card during an Evil Twin attack to try to reproduce it.
> 
> Keep in touch.

You go to google search v2.86 (dnsmasq: config error is REFUSED (EDE: not ready)
many people have this problem.

**Comment by Casper-88** [comment] 2022-03-11 14:17
@OscarAkaElvis 
You go to google search v2.86 (dnsmasq: config error is REFUSED (EDE: not ready)
many people have this problem.

**Comment by OscarAkaElvis** [comment] 2022-03-11 14:24
Ok test done... It seems I already have a kali... upgraded it and then tested it with a wireless card using the evil twin attack... no issues as you can see on next screenshot:

![image](https://user-images.githubusercontent.com/5803348/157885764-c6205246-22ca-434e-bc47-82d8924f551d.png)

And the victim (my phone) entered into the fake network and the captive portal was triggered fine... so the DNS blackhole is working fine.

Whatever is happening to you... sorry but I must say that is not related to airgeddon. Can't reproduce your issue. Closing.

**Closed by OscarAkaElvis** 2022-03-11 14:24 UTC
Labels: investigating

**Comment by Casper-88** [comment] 2022-03-11 14:35
@OscarAkaElvis 
I use handphone captive portal was triggered fine, 
Use laptop connect will show dnsmasq: config error is REFUSED (EDE: not ready).
I think nevermind.
