### ISSUE TITLE
Unable to Detect a Graphical Interface in Kali Windows Subsystem

### ISSUE THREAD

**Issue by eku952** [v1s1t0r1sh3r3/airgeddon#129] opened 2018-05-01 13:39 UTC
Script version: 8.01
OS: Kali on the Windows Linux Subsystem

Airgeddon fails to detect a graphical interface on the Kali Windows Subsystem even after the installation of a graphical interface. The script also fails when attempting to use it in the xfce4 RDP interface.

![image](https://user-images.githubusercontent.com/14254199/39474706-e0da51f6-4d1a-11e8-8ff9-90108322fad3.png)

![image](https://user-images.githubusercontent.com/14254199/39474758-1f04b430-4d1b-11e8-8713-71d488ec7d2c.png)

**Comment by v1s1t0r1sh3r3** [comment] 2018-05-01 21:37
Sorry but Linux under Windows subsystem are not supported. Anyway, some people got that part (X connecting correctly) working but anyway they have errors on the next steps like detecting the network cards... you can see that problems here:

https://github.com/v1s1t0r1sh3r3/airgeddon/issues/127
https://github.com/v1s1t0r1sh3r3/airgeddon/issues/128

Closing.

**Closed by v1s1t0r1sh3r3** 2018-05-01 21:37 UTC

**Comment by bperl03** [comment] 2018-09-21 11:06
the same problem on kali linux for raspberry pi 3 version 8.11

**Comment by v1s1t0r1sh3r3** [comment] 2018-09-21 16:16
I have a rpi3 with kali working fine. Check if you have xdpyinfo command available. If not, install using apt x11-utils package. Check also if you have xset command. If not, same process install it using apt. It is included in x11-xserver-utils package. Hope it helps.

**Comment by bperl03** [comment] 2018-09-22 13:46
it's not working first I run it on Kali sticy fingers re4son kernel now I change to stock nexmon Kali 4.4.50-V7+ and still not work I check'd the xset and xdpyinfo  and they installed , thanks for comment

**Comment by v1s1t0r1sh3r3** [comment] 2018-09-22 15:00
did you tried `xhost +` command before launching airgeddon? usually is not needed but it seems you have custom stuff. The standard kali installation for rpi3 is working flawlessly. Good luck!

**Comment by bperl03** [comment] 2018-09-22 18:52
I'm sorry to wasting your time, the problem is I'm connecting to Kali from ssh and the ssh need option -X and authorization to interactive with X that's it , thanks

**Comment by ajtazer** [comment] 2020-07-07 13:29
> 
> 
> Sorry but Linux under Windows subsystem are not supported. Anyway, some people got that part (X connecting correctly) working but anyway they have errors on the next steps like detecting the network cards... you can see that problems here:
> 
> #127
> #128
> 
> Closing.

Still Not Supported?

**Comment by OscarAkaElvis** [comment] 2020-07-07 15:16
Yeah, not supported. That kind of abomination probably never will be supported.
