### ISSUE TITLE
Evil Twin doesn't launch AP on RTL8187 device

### ISSUE THREAD

**Issue by Eyeless77** [v1s1t0r1sh3r3/airgeddon#44] opened 2016-12-02 16:24 UTC
I use Alfa Networks WiFi Adapter (AWUS036H, RTL8187 chipset). Your script uses hostapd to launch AP, which requires AP-mode to be supported, but RTL8187 supports only IBSS, managed and monitor mode. So when I launch the Evil Twin attack, I've got all xterm windows open (dhcpd, sslstrip and so on) and here is the listing of hostapd window:

Configuration file: /tmp/ag.hostapd.conf
nl80211: Could not configure driver mode
nl80211: deinit ifname=wlan0 disabled_11b_rates=0
nl80211 driver initialization failed.
wlan0: interface state UNINITIALIZED->DISABLED
wlan0: AP-DISABLED 
hostapd_free_hapd_data: Interface wlan0 wasn't started

All background processes such as sending deauth messages are working but AP doesn't start. Is there a chance to change the method of launching AP (airbase-ng e.g.) or catch this issue on startup?

Thank you.

**Comment by v1s1t0r1sh3r3** [comment] 2016-12-02 19:04
I use alfa with RTL3070 chipset and everything goes fine in every linux... I can't reproduce the issue because I don't have that chipset... anyway, to launch hostapd is in managed mode (the script does the change if necessary) and hostapd puts it automatically on master mode... I really think is more a driver problem of your distro with that chipset and is not related to script.

What distro are you using? Did you try your hardware in other distro? you can test this easily using any live distro like Kali or Parrot or any other. I'll be waiting for your feedback.

**Comment by Eyeless77** [comment] 2016-12-06 17:05
I tried Kali and Parrot:
Linux kali 4.3.0-kali1-amd64 #1 SMP Debian 4.3.3-7kali2 (2016-01-27) x86_64 GNU/Linux
Linux parrot 4.7.0-parrot-amd64 #1 SMP Parrot 4.7.6-1parrot0 (2016-10-21) x86_64 GNU/Linux

Yes, it's all about chipset: https://wikidevi.com/wiki/Wireless_adapters/Chipset_table

RTL8187 doesn't support AP mode, but RT3070 does and your config is working. I am asking if there is a chance to launch an AP not by hostapd but maybe in some other way? Or master mode support is mandatory?

**Comment by v1s1t0r1sh3r3** [comment] 2016-12-06 17:12
To create an Access Point? I think so... not sure right now... maybe you can try to create an AP manually with airebase and check with "iwconfig" the mode of the card while doing it to be 100% sure. I will try if I have time, not now sorry.

Anyway, before creating the script I was doing some tests and airebase was discarded because I got a lot of fails and problems... hostapd was more stable and successful on my tests.

**Comment by kcdtv** [comment] 2016-12-06 17:37
he only alternative I know for RTL8187l is airebase-ng.

**Comment by v1s1t0r1sh3r3** [comment] 2016-12-07 00:18
Yes, Kcdtv is right. I did some tests and with airbase-ng you can set up using monitor mode. But is a pain in the ass to include it on the script now. I can't promise you anything... we are developing right now WPS stuff... maybe later.

**Comment by v1s1t0r1sh3r3** [comment] 2016-12-27 10:50
Sorry, closing this enhancement proposal. Finally is not going to be developed.

**Closed by v1s1t0r1sh3r3** 2016-12-27 10:50 UTC
Labels: enhancement

**Comment by karacaefendi** [comment] 2019-04-09 21:28
++

**Comment by djdisikd** [comment] 2019-05-06 03:20
It supports ap mode
