### ISSUE TITLE
Explore targets does'nt work anymore

### ISSUE THREAD

**Issue by venethia** [v1s1t0r1sh3r3/airgeddon#612] opened 2024-08-20 12:15 UTC
#### What is your airgeddon version?

11.30

#### What is your Linux O.S. and which version?

Kali 6.8.11-1kali2 (2024-05-30) updated 

#### Is your O.S. running in native mode or is a virtualized system? in that case, VMware? VirtualBox? Other?

WMware workstation player 17.5.2 build-23775571 on Windows 11 23H2.

#### Which is the chipset of your wireless card?

MediaTek MT7612U

#### Describe the issue and the steps to reproduce it

Never had problem until today.

The wireless adapter Alfa AWUS036ACM has always worked well. The 'secret' was to plug the usb adapter only after the VM was running. It worked perfectly for 1 year. Now the adapter is correctly recognized from Linux (command: lsusb) and from Airgeddon. I can set the monitor mode on without problem. But when I try to explore for targets nothing done. All blocked.

I keep blocked `here:

``
WPA/WPA2/WPA3 filter enabled in scan. When started, press [Ctrl+C] to stop... 
Press [Enter] key to continue...
``

I don't have problems with other wifi tools.

Thanks in advance.

**Comment by OscarAkaElvis** [comment] 2024-08-20 12:33
Ok this is a known problem caused by a bug in the modern bash package (in version 5.2.21 as far as I know). For some reason, the xterm windows are opened in a collapsed way. This way:

![image](https://github.com/user-attachments/assets/669b4364-d7d3-41c7-bd32-1d4edfc8028c)

You can just expand it and you'll see that everything is ok. This is a non-related to airgeddon problem. The bug is not ours. Anyway here you are some workarounds until they fix it:

1. Go to your airgeddon dir using cd command (where you cloned it, or on /usr/share/airgeddon if got it by apt), and launch it this way: `bash --posix airgeddon.sh` . You'll see the windows are opening again as normal.
2. Just use it as it is and expand the windows manually
3. Set tmux instead of xterm on the airgeddon options or setting it manually on the hidden .airgeddonrc file as explained [here](https://github.com/v1s1t0r1sh3r3/airgeddon/wiki/Options). I mean, setting `AIRGEDDON_WINDOWS_HANDLING=tmux`

We should be patient until the problem is fixed. I know that @alexl83 already reported it somewhere. I'll close this because as I said is something out of our hands and our scope.

**Closed by OscarAkaElvis** 2024-08-20 12:33 UTC

**Comment by OscarAkaElvis** [comment] 2024-08-27 18:18
I saw you @alexl83 created a patched version of the "broken" bash 5.2.21 package and put it on your GitHub repo. I tested it and it works well. I'd recommend to use this instead of the `--posix` workaround because the `--posix` stuff is changing the behaviour of some things inside airgeddon and could cause errors on some things (even if the xterm windows are opening well).

So the best advice I'd give is:

1. Just download the bash fixed package from here: https://github.com/alexl83/alexl83.github.io/raw/main/pool/main/b/bash/bash_5.2.21-2.1+b3_amd64.deb
2. Install it on your debian based system (I tested it on Kali Linux and it worked very well) using `dpkg -i bash_5.2.21-2.1+b3_amd64.deb`
3. Wait until an official fix come from Debian

Thanks for your work on this @alexl83 . Great contribution! 🤟

**Comment by youthanazia** [comment] 2024-09-07 12:18
Hi, 

https://github.com/alexl83/alexl83.github.io/raw/main/pool/main/b/bash/bash_5.2.21-2.1+b3_amd64.deb

Is there a fix for 32bit/i386?

Thanks

**Comment by OscarAkaElvis** [comment] 2024-09-07 12:56
Maybe you can use the `bash --posix airgeddon.sh` . Not sure if @alexl83 compiled it for 32bits. At least is not in the repo.

**Comment by youthanazia** [comment] 2024-09-07 13:35
Ok, thanks for your help.

**Comment by youthanazia** [comment] 2024-09-09 09:33
5.2.32 i386 works great. 

Thank you

**Comment by JoaoMSacramento** [comment] 2024-10-28 11:40
Is there a fix to ARM64?

**Comment by OscarAkaElvis** [comment] 2024-10-28 12:32
@JoaoMSacramento , you didn't check closely his repo. It has packages also for arm64: https://github.com/alexl83/alexl83.github.io/blob/main/pool/main/b/bash/bash_5.2.32-1%2Bb1_arm64.deb

**Comment by OscarAkaElvis** [comment] 2025-01-02 10:54
It seems the problem is not going to happen anymore. I updated today a Kali vm and bash 5.2.37-1 was installed. The bug is not happening anymore on that version and hopefully will not happen also on later versions

**Comment by Aggelos11** [comment] 2025-01-15 18:42
> It seems the problem is not going to happen anymore. I updated today a Kali vm and bash 5.2.37-1 was installed. The bug is not happening anymore on that version and hopefully will not happen also on later versions

Does deauthentication works well for you ? For me the targets are not deauthenticated

**Comment by OscarAkaElvis** [comment] 2025-01-17 05:31
Please, don't hijack non-related issues. That has nothing to do with this thread. Connect to discord server to keep asking.
