### ISSUE TITLE
Evil Twin doesn't work with internet connection and 2 wifi interfaces

### ISSUE THREAD

**Issue by its0x08** [v1s1t0r1sh3r3/airgeddon#76] opened 2017-04-14 23:58 UTC
- Please, answer the questions to provide maximum of info.
 - Answer ALWAYS in english.
 - If more info is needed and requested by airgeddon staff but there is no answer in 10 days, the issue will be closed.

#### What is your airgeddon version?
v6.12 

#### What is your Linux O.S. and which version?
Linux k4li 4.9.0-kali3-686-pae #1 SMP Debian 4.9.18-1kali1 (2017-04-04) i686 GNU/Linux

#### Which is the chipset of your wireless card?
rt2800usb
Ralink Technology, Corp. RT2870/RT3070

#### Describe the issue and the steps to reproduce it

*EvilTwin attack doesn't work with two interfaces in the same time!
I tried to use one interface as in monitor mode and anothre to provide internet but the one that provide internet 
never works!
I think it doesnt because after I put all parameters of the attack and I press ENTER to start it the NetworkManager process gets killed .. thats why it doesn't provide internet!

Thanks in advance!

**Comment by v1s1t0r1sh3r3** [comment] 2017-04-15 09:42
It works with two interfaces at the same time... maybe you want to say "doesn't work with two **wireless** interfaces at the same time". In that case I reproduced the problem.

Here there is an important conflict. The hostapd to create fake AP conflicts with Network Manager. If you stop Network Manager, you can create fake AP, but if you don't stop it, you can't create the fake AP. In theory, with Network Manager version higher or equal than 1.0.12 , you can put cards in monitor mode without loosing the internet connection. This is already implemented on airgeddon. It is suppossed than the Network Manager version is detected an checked to know what to do. Anyway, as I said, it seems the problem is not to put the card in monitor mode, the problem is because Hostapd.

Ah, another curious thing. After failing on the scenario you proposed, if you try the attack again without exiting airgeddon it works! so I think it has solution.


Let me some days to investigate it more deeply.

**Comment by its0x08** [comment] 2017-04-15 20:08
I tried firstly with ethernet but it doesn't detect the internet at all it says "It seem like there is no internet connection" or smth like this… that's why I tried 2 wifi cards... But still no luck...
Maybe airbase is better than hostapd in this case..

**Comment by v1s1t0r1sh3r3** [comment] 2017-04-15 20:57
I don't think so. I did tests with airbase and the performance is worse.

With ethernet for internet interface it works like a charm. Check your ethernet-internet interface and try it again. Be pretty sure of having internet connection on that ethernet interface. You will see it works very well.

Anyway, I'm investigating a little bit about this and is not easy to fix. Sometimes it works and sometimes it doesn't with 2 wireless cards (one connected to internet and other for hostapd)... so I need to do more testing.

**Comment by its0x08** [comment] 2017-04-15 22:40
My ethernet cable is pretty good/fast ..!
Its a fiber optics and it good working, when it comes to airgeddon it says there is no internet connection. 
In any case if u kill the NetworkManager process there will be no internet over ethernet either I think...

**Comment by v1s1t0r1sh3r3** [comment] 2017-04-15 22:41
Ohh man. I did a lot of tests... and sadly, it seems finally **it has no solution**. hostapd needs no conflicting processes, to work with hostapd there are only two alternatives: airmon-ng check kill (is what airgeddon is doing) or stop network-manager. Any of them is ok for hostapd but sadly if your internet connection depends of network-manager automatically is stopped and there is no internet connection anymore. This seems a blocking point. So you have these workarounds:

 - You can get internet from ethernet interfaces. <- you said it didn't worked for you but believe me, it works. You are doing something wrong on this point.
 - You can install a virtual machine using virtual box or vmware on which your host's wireless card is going to be detected as eth0 on the virtual machine (this always happens). In this way you can have internet through wireless because for the Linux system is an ethernet card (usually eth0) and you can use another wifi card for hostapd.
 - You can use a system on which there is no network-manager and connect to internet with one of your wifi card using a different method.

Thank you for your report. Closing.

**Closed by v1s1t0r1sh3r3** 2017-04-15 22:41 UTC
Labels: bug, investigating

**Comment by kcdtv** [comment] 2017-04-16 13:44
To sum-up the situation what you want to do, beyond the hacking, is to "use a computer as a wifi repeater with two wifi interfaces, one to connect, one to repeat"
So, first of all, **you do not need** (and do not want) network manager to connect to the wifi network with one interface.
First step would be to connect directly with wpa_supplicant (don't forget that network manager is just a wrapper for wpa_supplicant, iwtools and a couple of other network command line).  
Maybe using nm_cli (comand line for network manager) is less conflictive, you can have a try, I wouldn't bet on it, but... why not? 
About ethernet conexion: you should not loose it normally with airmon-ng check kill or stopping network service.  Nevertheless, if it is lost it is very simple to reconnect
`ifconfig <interface> up && dhclient <interface>`
Ethernet connexion is kind of primitive compared with WiFi.

**Comment by its0x08** [comment] 2017-04-17 09:12
Nvm man he looks like he doesn't want to solve the problem!
@kcdtv

**Comment by v1s1t0r1sh3r3** [comment] 2017-04-17 09:20
It is not a matter of "wanting to", just this can't be done.

**Comment by kcdtv** [comment] 2017-04-17 13:20
@its0x08 
Well, my message was more for you than for v1s1t0r :smiley_cat: 
In case you wanted to investigate and/or participate. 
I believe it is more productive than complaining and waiting for things to be done...

**Comment by its0x08** [comment] 2017-04-19 10:48
Here is the proof!!👏👏👏 http://i.imgur.com/PY2qcVU.jpg

**Comment by v1s1t0r1sh3r3** [comment] 2017-04-19 12:51
There is something wrong on your side. That only proof that you don't have internet access on eth0, but that is not an airgeddon issue.

There is a function on airgeddon called check_internet_access which checks if you have internet connection or not. How airgeddon is doing that? with a ping command. This is what airgeddon is executing `ping -c 1 github.com -W 1` and if the exit code of that is a 0 everything is ok (as always in bash).

Try this:
1. Disconnect all wireless interfaces or shutdown network-manager or however. Let only cable and eth0.
2. Don't start airgeddon because is not airgeddon related, launch this command on a standard console and check the output `ping -c 1 github.com -W 1; echo $?`
3. If is a 0 everything is ok and in airgeddon you should be detected as having internet access. If is a 1 you have a problem you must solve on your Operating System.

Can be only 3 possible causes:

 - You don't really have internet access on that interface.
 - You are filtering ICMP traffic (is what ping uses) on your router or wherever.
 - You are not resolving ok github.com or you have a DNS related problem.

So be pretty sure of be able to ping github.com from console before starting airgeddon.

**Comment by kcdtv** [comment] 2017-04-19 13:01
I believe the script just ping a server or something like this to determine if you "have Internet access"...  
...Yes indeed: 
```
#Check for active internet connection
function check_internet_access() {

	debug_print

	ping -c 1 ${host_to_check_internet} -W 1 > /dev/null 2>&1
	return $?
}
```
And the host is
`host_to_check_internet="github.com"`
So...
... Maybe you had some very low latency at this moment? It is just one packet, maybe it got lost, try again.,   
Try to ping github in a shell to see what happen.

**Comment by xtonousou** [comment] 2017-04-19 17:02
First of all, does `ping` work out of the box? Maybe is a capability issue. It requires `cap_net_raw` to work.

**Comment by its0x08** [comment] 2017-04-20 08:23
@v1s1t0r1sh3r3 I think is ICMP problem !
but that doesnt mean I got no internet on that interface. Mine is fiber optics man it downloads 18 gb in 20-25 minutes. So I thing is wrong the way of checking the internet connection.
I guess alot of people may have this problem that i have... Its not me btw is my ISP blocking `ping` :( 
maybe u can make an IF statement so IF PING is OK.. continue. ELSE "curl ipinfo.io/ip"
and this is better i think!!!!
give it a try bcz we cant determine if there is internet or not by pinging !
thanks in advance ...

**Comment by v1s1t0r1sh3r3** [comment] 2017-04-20 09:47
Ok, I'll take it in consideration for next release. I'll do more than one kind of check. Thanks.

In the meanwhile, you can do a return 0 always on that function if you are pretty sure you have internet access and is going to work for you.

**Comment by xtonousou** [comment] 2017-04-20 11:13
@its0x08 Seriously, did you try using `ping` on same connection from different machine? If it does not work, maybe your router's firewall is blocking ICMP or `ping` does not have tha appropriate capabilities. The connection speed is crucial when it is very slow like < 50KiB.

**Comment by its0x08** [comment] 2017-04-20 21:40
I didnt check the code of the tool @xtonousou  so I didnt know the way he use to check connection!
Now that he mentioned I understand that for me it wont work because my ISP blocks `ping`
thats why I suggested him an other way of checking connection!
Is not that Im trying to lie or smth, because it looks like u guys are against what I say and try to protect the coder, Im not against u guys. If Im making or commenting on an ISSUE it means I try to help making this tool better !

**Comment by v1s1t0r1sh3r3** [comment] 2017-04-21 06:52
Ok I think I'm going to lock this conversation. This is not a forum. Everything is clear here. For future versions additional checks will be done in addition to ICMP. Thanks again for your report.
