### ISSUE TITLE
WPS force attack if have timeouts

### ISSUE THREAD

**Issue by mrochaaa** [v1s1t0r1sh3r3/airgeddon#310] opened 2019-10-05 20:06 UTC
Sometimes, with bruteforce attack, for instance "bully" can try 10 pins and after just have "timeouts", but if you stop the attack and you restart attack, bully can try fast and perfect more 10 pins without fails, I find this is because weak signal etc, but anyway, stoping and restarting attack, bully can try more 10, and more 10, and more 10 pins. So I suggest add an little "new wps attack" to set the maximum timeouts to bully (or reaver) automatically stop, pause some time (an custom time) and restart attack, this can work like an "enforce attack in weak signal" because doing so attack can flow anyway. This issue also happen when trying the second part of pin, and restarting, bully try more 8 or 10 pins, the same behavior. For instance I can set if have 3 timeouts, pause 5 or 10 seconds... and restart

**Comment by OscarAkaElvis** [comment] 2019-10-05 20:19
What is this? a suggestion? an issue? closing due issue creation policy. You didn't filled up the template.

Whatever is related to reaver or bully is related to reaver or bully, not to airgeddon. And I must say i'm not able to reproduce that because it will depend on the combination of all the stuff (your card, driver, your ap). Modifying only one of these elements the behavior is completely different. So... if you found a way to work with your combination, good for you! but we are not going to implement stuff if we can't reproduce it. Closing.

**Closed by OscarAkaElvis** 2019-10-05 20:19 UTC
