### ISSUE TITLE
Problem with wep all in one attack

### ISSUE THREAD

**Issue by TheBesk** [v1s1t0r1sh3r3/airgeddon#279] opened 2019-07-22 09:11 UTC
#### What is your airgeddon version?

v9.20

#### What is your Linux O.S. and which version?

Debian 9

#### Which is the chipset of your wireless card?

Qualcom Atheros QCA9565 / AR9565

#### Describe the issue and the steps to reproduce it

In the wep all in one attack the fake authentication with aireplay fails when the network name has spaces in the middle.
For example, if the network name is "my wifi" the aireplay command will be:

`aireplay-ng -1 3 -o 1 -q 10 -e my `and the name of the network interface
But this, of course, doesn't work (the network ssid is cut off to the space character).
A solution to this problem could be using the mac address of the access point instead of the ssid.
So the command will be:
`aireplay-ng -1 3 -o 1 -q 10 -a 00:00:00:00:00:00`

**Comment by OscarAkaElvis** [comment] 2019-07-22 09:35
I'll try to reproduce it but it seems at first sight checking code that that can't happen in airgeddon. This is the piece of code launching Fake AP auth

![image](https://user-images.githubusercontent.com/5803348/61622083-61e39780-ac74-11e9-88b7-d14621e1d110.png)

As you can see, the ssid is between quotes and it should support spaces. the `-a` argument is also used.

**Comment by OscarAkaElvis** [comment] 2019-07-22 20:44
Problem reproduced.

![image](https://user-images.githubusercontent.com/5803348/61663982-1f50a800-acd2-11e9-8c4e-fe024c925b56.png)

Probably the problem is caused due too many quotes inside quotes because of the tmux integration.

**Comment by v1s1t0r1sh3r3** [comment] 2019-07-22 21:37
@TheBesk You are right. Removing `-e` parameter is enough. As it was said before on this thread, the `-a` to send BSSID is already used, so not need to use `-e` param. Now it works like a charm even with a ESSID containing a space as you can see here:

![imagen](https://user-images.githubusercontent.com/17899365/61666668-6772c900-acd8-11e9-8c85-b2db8059989e.png)

This fix will be released on next 9.21 version. Thanks for the report. Closing.

**Closed by v1s1t0r1sh3r3** 2019-07-22 21:37 UTC
Labels: bug, work in progress

**Comment by ankyw7** [comment] 2019-07-25 06:41
When ever i am trying Wps attack menu it not showing any Bssid of WiFi & When i am trying to attack in other option this WiFi is showing in other attack please help me to find the problem .


Thanking you.

**Comment by OscarAkaElvis** [comment] 2019-07-25 06:46
What you are talking about is not related to this issue. Locking.
