### ISSUE TITLE
Xterm Window in corner of display

### ISSUE THREAD

**Issue by Stenvro** [v1s1t0r1sh3r3/airgeddon#614] opened 2024-08-31 07:55 UTC
#### What is your airgeddon version?

Airgeddon 11.30 All dependencies installed 

#### What is your Linux O.S. and which version?

Kali Linux 2024.3

#### Is your O.S. running in native mode or is a virtualized system? in that case, VMware? VirtualBox? Other?

Os is running native on dell laptop 

#### Which is the chipset of your wireless card?

multiple wireless cards all work perfect alfa awus 036 ach / acm

#### Describe the issue and the steps to reproduce it

For some reason when airgeddon is opening a xterm window it will spawn in the corner of the display very tiny. 
it doesnt even have any textlines on it if multiple windows are opened they will spawn in a diffrent corner. some windows i can make larger and see the contents of it but for some windows the text wil be displayed verticaly on only one line. if i open a xterm window from my terminal it opens just fine in the center of the screen on startup of airgeddon it detects the right display config so that looks all good 

first picture airgeddon startup
seccond xterm display opened top right 
third one what happens if i make it bigger this one is readable 

https://imgur.com/a/DeHtXLR

**Comment by OscarAkaElvis** [comment] 2024-08-31 08:56
Hi. It is not an airgeddon bug. It is a Debian's bash package bug. This is a duplicate of this: https://github.com/v1s1t0r1sh3r3/airgeddon/issues/612

On that link you can find everything you need to know: the cause, the workarounds, the link to Debian bug-tracker, even a patched bash package to work flawlessly until there is an official solution.

Closing.

**Closed by OscarAkaElvis** 2024-08-31 08:56 UTC
