### ISSUE TITLE
airgeddon.sh: line 13725: /tmp/ag1/wps.txt: No such file or directory

### ISSUE THREAD

**Issue by tuxarch** [v1s1t0r1sh3r3/airgeddon#618] opened 2024-09-08 04:26 UTC
#### What is your airgeddon version?

v11.31

#### What is your Linux O.S. and which version?

arch linux, airgeddon installed via repository blackarch

#### Is your O.S. running in native mode or is a virtualized system? in that case, VMware? VirtualBox? Other?

native mode

#### Which is the chipset of your wireless card?

Qualcomm Atheros AR9462 Wireless Network Adapter [168c:0034] (rev 01)
Rivet Networks Killer Wireless-N 1202 Half-size Mini PCIe Card [1a56:2003]

#### Describe the issue and the steps to reproduce it

WPS attacks menu --> Explore for targets --> error airgeddon.sh occurs: line 13725: /tmp/ag1/wps.txt: No such file or directory but file exists.

![screen-1725768827](https://github.com/user-attachments/assets/99f1ab4e-c19c-49f4-9531-82fe275b848a)
![screen-1725768863](https://github.com/user-attachments/assets/670bde64-ec5a-4e8f-bbd4-9b5fb5ffb812)

**Comment by OscarAkaElvis** [comment] 2024-09-08 08:23
Hi, sorry but I can't reproduce your problem even using BlackArch. The line of the error is containing this on that airgeddon version:

`readarray -t WASH_PREVIEW < <(cat < "${tmpdir}wps.txt" 2> /dev/null)`

So as the file is existing, it should be ok, even if it is empty I think. Anyway, it could be good to know the content of the wps.txt file as soon as you get the error. Please, paste it here if you can. Just a cat command to see its content is ok.

I saw that kind of behavior before when airgeddon is used with bad wifi adapters. So your problem is probably related to the wifi adapters you are using.

Sadly, I can't guarantee 100% that because that adapters are not present on our known list. But as I said, probably they are causing the problem like others from the blacklist are doing. Check the list:

https://github.com/v1s1t0r1sh3r3/airgeddon/wiki/Cards%20and%20Chipsets

Get a good adapter with a hacking compatible chipset. I'm pretty sure it will work well. As you can see there is only one Atheros chipset which is working good for wifi hacking (the one in the whitelist). So, probably the chipset of your adapters are not good for wifi hacking. Actually, if you could get a whitelisted card/chipset and confirm that everything works ok with it, I'd add both of your chipsets to the blacklist.

On the given link you can find the whitelist containing the known good chipsets. Even you can find direct links to buy them on Amazon.

I'd like to continue the discussion in Discord where you maybe could add more data, like if your chipsets are VIF compatible or not (to be able to add them to the right list on wiki). More info about what is VIF and how to know if the adapters are compatible here: https://github.com/v1s1t0r1sh3r3/airgeddon/wiki/FAQ%20&%20Troubleshooting#what-is-vif

I know VIF capability is used only for Evil Twin attacks in airgeddon, but anyway it would be good to know as much as possible from these chipsets, as I said to add them to the right list.

To connect to our Discord server, you can find the invitation link on contact section at wiki. Thanks for the report.

**Comment by OscarAkaElvis** [comment] 2024-09-17 20:36
Closing due to the lack of info.

**Closed by OscarAkaElvis** 2024-09-17 20:36 UTC
Labels: waiting for info
