### ISSUE TITLE
It should check if specific device has Hotspot support before continuining

### ISSUE THREAD

**Issue by HassanMirza01** [v1s1t0r1sh3r3/airgeddon#272] opened 2019-07-05 08:56 UTC
#### What is your airgeddon version?
9.20

#### What is your Linux O.S. and which version?
Ubuntu 18.04.2 LTS

#### Which is the chipset of your wireless card?
Laptop's Chipset= Intel Corporation Wireless 3165 (rev 81)
For injection Support, Using= Ralink Technology, Corp. RT2870/RT3070

#### Describe the issue and the steps to reproduce it
So it goes all well in start, i have all dependencies fulfilled, but issue came when Airgeddon tried to start Hostapd-wpe on the RT-3070, as i chose RT-3070 to start and use injection, as my Laptop's wifi card doesn't support Injection, just Monitor mode supported, 

So i want to ask if there can be a check or option to choose on which interface we want to start hostapd or it list those chips in system which support hostapd mode...

**Comment by OscarAkaElvis** [comment] 2019-07-05 09:37
I see you have a Ralink 3070 which is valid to launch any airgeddon attack. Just select it in order to work.

These days there are few cards supporting monitor mode without ability to inject... so I think it doesn't worth the time. Thanks anyway for your suggerence. Closing

**Closed by OscarAkaElvis** 2019-07-05 09:37 UTC
Labels: dismissed, feature enhancement

**Comment by HassanMirza01** [comment] 2019-07-05 09:49
i am using only Ralink 3070 for attack, its deauthenticating users from networks with ease but what am trying to say it doesn't have hotspot support, so i cannot use hostapd-wpe attack with this chip but i have hotspot feature in my laptop's wifi card... how that could be achieved ??

**Comment by OscarAkaElvis** [comment] 2019-07-05 09:59
I tested it using exactly the same chipset (Ralink RT3070) and it worked like a charm. I created a fake AP using enterprise attack and everything is working... so the problem is neither airgeddon nor the chipset. Clearly is your driver. Try using another one. I did my test using Parrot Linux. I hope this info can help you. Good luck!

**Comment by HassanMirza01** [comment] 2019-07-05 10:29
Bro, i am getting this... Any idea ?? wlan0 is Ralink 3070 in monitor mode as selected before.
![image](https://user-images.githubusercontent.com/26677817/60716740-9861a880-9f39-11e9-83fb-afde80b81c01.png)

**Comment by OscarAkaElvis** [comment] 2019-07-05 10:55
This is a captive portal attack which is using hostapd and not hostapd-wpe as you described. Anyway, it should be the same... the fake ap window (upper left in green) should show "AP-ENABLED" and it seems for you is not working for some reason... maybe you can try to execute manually on other window before launching the attack this command `airmon-ng check kill` but not sure if it could be related to your problem. If it doesn't work for you I can recommend to you to use another driver. It works flawlessly on Kali or Parrot Linux for example.

**Comment by HassanMirza01** [comment] 2019-07-05 11:25
do you think its looking for wlan0 interface to work but due to monitor mode, the name of wlan0 interface is changed to wlan0mon, ?? or what if i change the wlan0 name to wlan0mon in script and will it work as ap in monitor mode ??

**Comment by OscarAkaElvis** [comment] 2019-07-05 11:35
If your card is compatible to airmon-ng , airgeddon will detect it and it will do using airmon-ng. If airmon-ng is used, the name of the interface will be changed from wlan0 to wlan0mon and viceversa... but that shouldn't be a problem because airgeddon is able to handle that.

I think you should remove elements to your tests... the problem is not related to airgeddon... so I can suggest to you to do tests without using it. Do stuff like this:

1. Open a terminal
2. `airmon-ng check kill` <- this could be necessary depending of your network manager version, so do it and you'll be fine
3. To create an AP, your card is not needed to be in monitor mode... it should be in managed mode and hostapd will change it to master mode... so you can avoid the `airmon-ng start wlan0` command.
3. Launch a hostapd: `hostapd /path/to/your/hostapd/config/file` <- choose a simple one just to test!
4. Check your hostpad screen... you should see "AP-ENABLED" if everything is going well. Otherwise try rebooting your computer and do this process the first thing before messing with it 😄 
5. You need to do whatever in order to be able to see "AP-ENABLED" on that screen... check your drivers, your hostapd configuration, etc.

Good luck!

**Comment by HassanMirza01** [comment] 2019-07-05 14:28
man i tried everything, but it seems like my RT3070 not supporting AP Mode, its Alfa-AWUS036NH device, and using rt2800usb drivers, if you got same, kindly perform the same attack and show me the AP working fine and enabled.
i chose RT3070 when it ask, and then i used Evil Twin attack, then i used Captive portal one,

**Comment by HassanMirza01** [comment] 2019-07-05 14:30
![Screenshot from 2019-07-05 19-12-12](https://user-images.githubusercontent.com/26677817/60729039-2c903780-9f5b-11e9-950d-957bd9ca8f03.png)

**Comment by OscarAkaElvis** [comment] 2019-07-05 15:54
Hi, yeah, mine is this: https://www.dx.com/p/alfa-1200mw-802-11b-g-n-long-range-54mbps-usb-2-0-wifi-wireless-network-adapter-w-antenna-green-2010335#.XR9tFI_taUk

So, it seems the same (is a green one). Alfa AWUS036NH, Chipset RT3070 and is working for me. In fact, I have also a TP-link adapter (TP-LINK TL-WN821N) with the same chipset RT3070 (https://www.ldlc.com/es-es/ficha/PB00108417.html?gclid=CjwKCAjw6vvoBRBtEiwAZq-T1YdrqI5D06smspb8W2A8vkigVxvAnGWpmDUWLV4lHUmobaz915KU1xoCt7wQAvD_BwE) and it is working as well.

My hostapd.conf file to test is a very basic one:

```
interface=wlan0
driver=nl80211
ssid=test
bssid=00:00:00:03:00:11
channel=1
```

I did my test on a Parrot Linux Vmware virtual machine as you can see here: 

![image](https://user-images.githubusercontent.com/5803348/60733102-3eb6a980-9f4c-11e9-9c94-6e4dfc7b6284.png)

Then, it is working fine:

![image](https://user-images.githubusercontent.com/5803348/60733322-cac8d100-9f4c-11e9-9aa5-dded44b9b4aa.png)

As you can see, firt attempt is failing because of network-manager. As I told you, it must be killed and then it works fine. And of course, Evil Twin or any other attack is working on airgeddon:

![image](https://user-images.githubusercontent.com/5803348/60733584-90abff00-9f4d-11e9-8696-ee93f93a64db.png)

You have something weird on your system. Download a Parrot or Kali Live cd, just to try! open it on your computer and try it, you'll see that it is ok and probably your card is ok... it is something on your Ubuntu but I don't know how more I can help, sorry. Do the test! using a live, just to discard hardware problem.

**Comment by HassanMirza01** [comment] 2019-07-05 18:24
thanks for the explanation bro, i have installed kali on my desktop pc but scared that its outdated now... well i will try on that too, not an issue.

But, in your screenshot, where it failed to start AP first time, then you killed network manager processes then it worked, is airgeddon killing network services too ?? cause i got AP-Enabled too while trying after killing those network processes... 
That means it could be enabled... i checked drivers for both ubuntu and kali, rt2800usb is the driver both using... seems like something enable the network manager in ubuntu while using airgeddon...

**Comment by OscarAkaElvis** [comment] 2019-07-05 18:37
airgeddon is handling everything, doing the airmon-ng check kill if needed based on network-manager version etc... maybe something new in Ubuntu is messing everything.... can you check that executing manually `airmon-ng check kill` from a different terminal while using airgeddon is making it to work?

Anyway give it a try on Kali. Ubuntu is a nice Linux but if you plan to work with wifi and hacking stuff, for sure is not the best choice as you can see 🙄 

Let us know if it worked using Kali

**Comment by HassanMirza01** [comment] 2019-07-05 18:52
i will try on Kali and report then... i hope i dont have to install all those softs again :D :P

**Comment by HassanMirza01** [comment] 2019-07-06 10:46
bro, i tried kali 2019.2 but the missing dependencies are like too time consuming to be fulfilled. so i tried Fluxion tool, script based for rogue ap attacks, and guess what, it successfully enabled AP on my RT3070 even while doing process... it ask for each interface to use for AP, Tracking SSID's, Attacking like that, i think you should look at it... 

At the end, fluxion was having some issues in starting captive portal but atleast it shows AP Enabled on my device...

**Comment by OscarAkaElvis** [comment] 2019-07-06 19:16
I deleted your comment. This is to talk about airgeddon and not to talk about other tools. Thanks. If you want to put here your test report ok, otherwise, you can talk about other tools on their pages or github repositories, thanks.

Regarding the dependencies... on Kali everything is available by apt, so is pretty straight forward to install all of them... just a command is enough.

**Comment by HassanMirza01** [comment] 2019-07-07 06:47
> I deleted your comment. This is to talk about airgeddon and not to talk about other tools. Thanks. If you want to put here your test report ok, otherwise, you can talk about other tools on their pages or github repositories, thanks.
> 
> Regarding the dependencies... on Kali everything is available by apt, so is pretty straight forward to install all of them... just a command is enough.

i tried to install simple tools like hostapd, dhcpd, lighttpd but not a single one of them was available by default repo in 2019.2. then i cloned hostapd-wpe repo to build it, i saw that pkg-config pkg also missing, and not available, i tried to build it too, then it came to openssl.h missing, libssl-dev was also not in repo... i left using kali then.

**Comment by v1s1t0r1sh3r3** [comment] 2019-07-07 08:12
All packages are removed from Kali repos?? They are basics... this Kali staff is crazy IMO. Maybe you should use Parrot instead, it has everything you need!

**Comment by HassanMirza01** [comment] 2019-07-07 09:06
Okay so victory here even on Ubuntu... tried all stuff, spent 2+ hours, killed network services too in separate windows but all got no success,

What worked for me, i just put the kill command above the hostapd command like this in script...
		${airmon} check kill
		command="hostapd \"${tmpdir}${hostapd_file}\""
		log_command=""

Now my RT3070 gets the AP enabled, even though my 2nd internet, the internal one also not working but thats not a big problem for me, 

retrieved password successfully from my home network...

**Comment by HassanMirza01** [comment] 2019-07-07 09:08
> All packages are removed from Kali repos?? They are basics... this Kali staff is crazy IMO. Maybe you should use Parrot instead, it has everything you need!

seems so... i found no pkg included in their official repo, weird stuff.... i ran update command successfully... dont know if its still needed to write the repo in their sources file... but kali sucks at this.... 
Happy with ubuntu with Unity... all working well now... 

If possible, integrate that kill command in upcomming versions, ahh, forgot to remind, it should just kill the selected interface :P

**Comment by v1s1t0r1sh3r3** [comment] 2019-07-07 09:13
Great news! for some reason... on Ubuntu the check kill is needed. Can you post your network-manager version here? You can check it launching this command: `NetworkManager --version` . Maybe I'll check on Ubuntu to make some modificiation when I have some free time to force on Ubuntu the airmon check kill... Thanks.

**Comment by HassanMirza01** [comment] 2019-07-07 10:52
> Great

hassanmirza01@bionic:~$ NetworkManager --version
1.10.14

**Comment by v1s1t0r1sh3r3** [comment] 2019-07-07 10:57
hhmmm.... it is supposed that with that version the check kill is not needed... over 1.0.12 should not be needed... quite weird. But for some reason in Ubuntu seems to be needed... I can force it... do this test please....

1. clone airgeddon master repository
2. go to a function called `check_if_kill_needed`
3. Modify the last line of the function (after all the conditionals and before exiting the function) and add this: `check_kill_needed=1`
4. Test it.

With that, the airmon-ng check kill is going to be done always... just to test. If it works for you, I'll do a modification to do a last check there if Ubuntu is the OS and if yes, I'll set it. In this way it will be force to all Ubuntu users. Bear in mind that this is a "brute" solution because killing network manager is going to cause to lost internet access if you have for example internet over another wireless interface...

Let us know the results please. Thanks.

**Comment by HassanMirza01** [comment] 2019-07-07 11:00
not a problem... wait a min, i have to clone repo again as i heavily modified the code... removed many things, removed time loop, removed many checks and Press Enter everytime for just my use as i want automated script... give me some seconds,..

**Comment by HassanMirza01** [comment] 2019-07-07 11:06
One more thing wanna ask... what about Hidden SSID networks ?? i read tutorial how to discover their names but when i tried with airgeddon, it says unable to identify WPA/WPA2 like stuff.... kindly check or confirm that

**Comment by HassanMirza01** [comment] 2019-07-07 11:14
> hhmmm.... it is supposed that with that version the check kill is not needed... over 1.0.12 should not be needed... quite weird. But for some reason in Ubuntu seems to be needed... I can force it... do this test please....
> 
> 1. clone airgeddon master repository
> 2. go to a function called `check_if_kill_needed`
> 3. Modify the last line of the function (after all the conditionals and before exiting the function) and add this: `check_kill_needed=1`
> 4. Test it.
> 
> With that, the airmon-ng check kill is going to be done always... just to test. If it works for you, I'll do a modification to do a last check there if Ubuntu is the OS and if yes, I'll set it. In this way it will be force to all Ubuntu users. Bear in mind that this is a "brute" solution because killing network manager is going to cause to lost internet access if you have for example internet over another wireless interface...
> 
> Let us know the results please. Thanks.

didn't worked... same appears, AP Disabled...

**Comment by HassanMirza01** [comment] 2019-07-07 11:18
man what i think, issue is the naming of Ubuntu to these Network Cards, like my RT3070 is given name like this, wlx000f002a3e20, when it we check kill it, its name gets shuffled or whatever, and ubuntu remain unable to find the interface used for AP and it says those errors,

**Comment by v1s1t0r1sh3r3** [comment] 2019-07-07 11:19
wtf??? did is forcing the airmon-ng check kill stuff.... did you noticed that while setting monitor mode, a new message appears saying "Please be patient. Maybe killing some conflicting processes..."

Are you sure you modified correctly the function? it should be in this way:

![imagen](https://user-images.githubusercontent.com/17899365/60767527-b1916300-a0b9-11e9-8f5b-c98c86758104.png)

Can you confirm both? the message appearing while setting monitor mode (it means that the kill is forced correctly) and the right function modification?

**Comment by HassanMirza01** [comment] 2019-07-07 11:25
i edited correctly, and yes it says forcing conflict process, now i am only setting up hostap.conf to see what actually causing it... cause there is something preventing it to use as AP Mode, may be different name, different interface, dont know, but it worked for many times... i didn't lose hope with ubuntu and trying from morning :D

**Comment by HassanMirza01** [comment] 2019-07-07 11:26
![image](https://user-images.githubusercontent.com/26677817/60767630-0510aa80-a0d4-11e9-95a9-b6f676908e92.png)

**Comment by v1s1t0r1sh3r3** [comment] 2019-07-07 12:55
Ok, but to be honest... I don't know what can be happening 😣

**Comment by HassanMirza01** [comment] 2019-07-07 13:02
i tried create_ap code, it enables hostapd successfully, its unmanagging devices before using them,,, may be thats culprit...

**Comment by HassanMirza01** [comment] 2019-07-07 14:26
> Ok, but to be honest... I don't know what can be happening

Issue solved... Ubuntu is the culprit, true...
After digging more deeper, i noticed in dmesg that ubuntu is renaming the interfaces on boot, like wlan0 to wlp2s0, wlan1 to wlx0000000 like that,

i found the fix, edited grub config and regenerated initrd, rebooted and BOOM, wlan0 and wlan1 are there working fine with stock airgeddon with no editing...

**Comment by OscarAkaElvis** [comment] 2019-07-07 16:17
Nice! Can you provide more details about ehat is needed to edit in order to avoid that starnge names in wireless network interfaces? Any information coukd be useful (a link or whatever). Maybe i can document it at wiki. Thanks.

**Comment by HassanMirza01** [comment] 2019-07-07 16:25
So for that, you have to open this file,
/etc/default/grub
Edit this line like that,

GRUB_CMDLINE_LINUX="" >> GRUB_CMDLINE_LINUX=" net.ifnames=0 biosdevname=0"

Then we have to update grub with this command,
sudo update-grub
After its done, Just Reboot...
Then you will see interfaces like wlan0, wlan1 and lile that, stock names,
Hope it helped...

**Comment by OscarAkaElvis** [comment] 2019-07-07 16:53
Awesome! I'll put a tip on Wiki about Ubuntu and the weird interface names. It worked like a charm. Thanks for your collaboration.

**Comment by HassanMirza01** [comment] 2019-07-07 16:55
Not a problem... Actually am also a script writter and i prefer scripts so i can just press 1 key and what i want should be done... 
I wrote many scripts for private use, like Burn isos to disk, gpt,mbr etc etc, 

So if i feel like something can be improved by me, i should... Thats what i did :)

**Comment by OscarAkaElvis** [comment] 2019-07-07 18:16
Done, now is documented at wiki: https://github.com/v1s1t0r1sh3r3/airgeddon/wiki/Compatibility

Check last point. Cheers!

**Comment by HassanMirza01** [comment] 2019-07-07 18:48
nice... and last question, how can i put my customized html file which shows to clients to enter password ??  i think lighttpd is doing that, not sure, but where ??

**Comment by v1s1t0r1sh3r3** [comment] 2019-07-07 18:54
You can customize evil twin. Everything is under /tmp/www dir. Check this issue: https://github.com/v1s1t0r1sh3r3/airgeddon/issues/74

**Comment by HassanMirza01** [comment] 2019-07-08 14:39
Bro, is there anyway i could use my 1 network interface while using other for attack ?? Now, RT3070 PERFORMING attack but my laptop's wifi is stopped.... Anyway there to use it for interrnet access??

**Comment by v1s1t0r1sh3r3** [comment] 2019-07-08 17:27
Yes can be in different ways. I think you are planning to use other Evil twin attacks (non-captive portal) on which internet access is needed. You can use your ethernet wired connection to give internet access as a first option. If you need internet access in a wireless device you must avoid to kill network manager, that's all. To do that, remove the "fix" what we talked in this thread to force the killing. It should work.

**Comment by HassanMirza01** [comment] 2019-07-08 17:37
No no, am not gonna use other attacks, actually while i keep evil twin running so someone joins and give me pass, i wanna use normal internet too and i dont have ethernet cable access for the moment... I removed that killing line check kill one, also the one used in fake_ap function but if i dont kill, ap cant start, and if ap started, i cant use my 2nd wlan0 interface which is not even affected.

**Comment by v1s1t0r1sh3r3** [comment] 2019-07-08 17:38
It works fine on other Linux distributions... remember that!

**Comment by HassanMirza01** [comment] 2019-07-09 13:12
hey bro, sorry to bother you again, i have some enhancement things... 
1. as you know not every router has same ip range, like TP link offer admin page at 192.168.0.1 so all TP link users will tends to use this ip when they see no internet instead of 192.168.1.1.
so there should be some detection thing or it should ask which ip range we wanna use...

2. I see in tips that in ap with sniff attack, we need internet in one chip and ap on other to give access to ap clients, so cant be same applied here, like when we enable ap on one chip, we can up the other one to access internet ??

3. In some devices, i see that the login page didn't appear automatically(some devices) in which we have to type ip manually while some phone require authentication immediately.. but what if someone try to use any website on ap connection nd that web redirects to our index.html page ?? so he got no way instead of typing pass to get access ??

I hope you will think about them... and tell me if you wanna implement...

**Comment by OscarAkaElvis** [comment] 2019-07-09 14:11
I think I'm going to lock this thread because this is for a concrete issue. It is not a helpdesk support.

Anyway, as a last answer for you I can say:

1. The kind of people which is able to be tricked into an Evil twin doesn't know anything about ip addresses... a user who is aware of this kind of things is not going to be tricked, so the ip stuff on the AP is pointless. In addition to that, what you propose lead into a creation and maintenance of an AP database setting the default ips for all of them. Something that is non-viable.

2. Yes, as we already told here, it works on other linux distributions... on all (excepting the captive portal) evil twin attacks, internet is needed and the clients are able to surf freely through your internet connection and that can be done using other interface. During a captive portal attack you still can have another (non-used in airgeddon for the attack) interface with internet access and it works perfectly.

3. We can't control which devices are following the standard of the captive portal detection. If some devices are not showing it automatically we don't know what can airgeddon to fix that. The "problem" is not in our side. Anyway, to see the portal is not needed to put the ip address of the portal. Opening a browser and typing any http (http is http, non https page) the captive portal will come up. Example, open browser and type: google.com <- note that this could fail if the user opened it before and his browser has cached that it needs https. If it doesn't work, clean cache and browser data or open a first-time-open website using http.

Thanks. Locking.
