### ISSUE TITLE
Can't connect to the Fake AP by airgeddon

### ISSUE THREAD

**Issue by sama4rem** [v1s1t0r1sh3r3/airgeddon#574] opened 2023-12-30 09:38 UTC
#### What is your airgeddon version?

Version [v11.21]
#### What is your Linux O.S. and which version?

Kali 2023.4
#### Which is the chipset of your wireless card?

SAGEM XG 762
#### Describe the issue and the steps to reproduce it

I can't connect to the Fake AP and I get this screen : 
![Screenshot_2023-12-29_17-49-37 (copy 1)](https://github.com/v1s1t0r1sh3r3/airgeddon/assets/155226791/ccfabe3d-e4b8-4abc-b81b-3044bc994c95)

On my phone I get 'Connection failed or can't obtain IP address'.
I have already performed this attack before and it worked with the same laptop and wifi adapter.
Thanks to the amazing team and developers .

**Comment by OscarAkaElvis** [comment] 2023-12-30 10:02
Hello, some questions for you:

Saying "fake AP", which kind of Evil Twin attack are you referring? captive portal? enterprise attack? 

When you say you performed this attack before, on what version of airgeddon? you still can download it from releases to test if you want... not so much changed about Evil Twin attacks lately, just the advanced captive portal was added. So probably, if it was working for you in the past maybe the problem is not related to airgeddon, maybe is on O.S., kernel or driver.

Anyway, are you seeing any VIF warning on airgeddon before launching the attack? because lately, airgeddon added this kind of check. Many people are receiving the warning but ignoring it which make the attack uneffective. Not sure that adapter (SAGEM XG 762) what chipset is using. You need to check it using `airmon-ng --verbose` to be sure about the chipset, it's important. Please, launch this command and paste here the output.

Regarding VIF, I hope that card you are using is supporting VIF, otherwise unintended behaviours like that could be happening. To know exactly what is VIF and how to check if your card is supporting it, please read this: https://github.com/v1s1t0r1sh3r3/airgeddon/wiki/FAQ%20&%20Troubleshooting#what-is-vif

If your card finally is not supporting VIF, that would be obviously the problem and it never worked fine in the past, in that case you just felt like it worked, but it didn't. It was just because airgeddon in the past was not complaining about that, but now it is checking for a valid VIF capable card.

I encourage you to join to our Discord channel to keep investigating about your problem. Invitation link to join is on contact section at wiki. There, it will be easier to investigate what is exactly happening because more people are involved on the channel willing to help.

**Comment by OscarAkaElvis** [comment] 2023-12-30 10:37
Ok, closing this as we saw the same request at discord channel. It will be handled there.

**Closed by OscarAkaElvis** 2023-12-30 10:37 UTC
Labels: waiting for info

**Comment by sama4rem** [comment] 2023-12-30 10:38
First, Thank you for your reply·
Yes the Captive portal attack.
I will check the VIF issue you suggested when i get back home. 
Before I did manage to capture the correct password the client entered on the fake captive portal. Now I can't even get the AP to work. 
I will be sure to donate to you guys if we fix the issue. Thanks again. I will get back to you later.

**Comment by OscarAkaElvis** [comment] 2023-12-30 10:39
yeah, no problem. Reply at discord. As I said, more people there able to help.
