### ISSUE TITLE
I can't see any network to monitor when Airgeddon is searching for target. 

### ISSUE THREAD

**Issue by doyoun0913** [v1s1t0r1sh3r3/airgeddon#333] opened 2019-12-24 04:43 UTC
I just downloaded the Airgeddon and tried to test out if it was working on my device. My system is Ubuntu 18.04 with dual-booted Windows, and I downloaded every essential tools and part of the optional tools (asleap, bully, hostapd-wpe, beef, mdk4, john, bettercaps, pixiewps, and hashcat  excluded). So I selected my wifi card, which supports both 2.4 and 5 Ghz,  changed my computer to be in the monitor mode, and I went to number 5 option- the handshake tools menu to explore the targets. Everything worked perfectly until I finally opened the monitor windows and realized no matter how much I wait, there will be no network to be detected. As far as I know, the area that I'm testing this should have at least 10+ networks with WPA/WPA2 encryption, and I just couldn't find "any" network on the window. I don't know what's the problem since I noticed that if I didn't have certain module uninstalled, the problem wouldn't have worked in the first place. I also noticed that when I enter the monitor mode, my computer disables the wifi connection; would this be related to the problem?

**Comment by OscarAkaElvis** [comment] 2019-12-24 15:39
Sorry but I'm going to close this due the issue creation policy violation. You didn't fill the template with all the needed data to try to help you.

Anyway I can tell you that you should try first out of airgeddon to set monitor mode and then to scan using airodump-ng to see if you see networks. Probably you'll not see any network in the same way as on airgeddon and probably the problem is not related directly to airgeddon. I invite you to join to our Discord channel to keep this discussion and to try to help you. You'll find the invitation link on the contact section of our wiki.

**Closed by OscarAkaElvis** 2019-12-24 15:39 UTC
