### ISSUE TITLE
Airgeddon doesn't detect BEEF.

### ISSUE THREAD

**Issue by MrBlaZe404** [v1s1t0r1sh3r3/airgeddon#625] opened 2024-09-28 15:29 UTC
#### What is your airgeddon version?

Latest version

#### What is your Linux O.S. and which version?

Linux Mint latest version

#### Is your O.S. running in native mode or is a virtualized system? in that case, VMware? VirtualBox? Other?

Bare metal

#### Which is the chipset of your wireless card?

Intel corporation comet lake PCH-LP CNVi WiFi

#### Describe the issue and the steps to reproduce it

I installed BEEF from its GitHub page, but Airgeddon doesn't detect it.

**Comment by OscarAkaElvis** [comment] 2024-09-28 15:45
Please, give more details. Saying that your airgeddon version is latest is like not saying anything. Latest version changes depending on your system, the repositories you are using or the branch you cloned from GitHub. So be specific.

Regarding the OS version... The same. The more details you provide, more possibilities to help you. 

Regarding BeEF, did you see the option to tell airgeddon where it is located? I bet no. Please, read the options from the menus. That option is precisely for your case, when you install it on a non-commin location, you must specify where it is to the tool.

In any case, this is not a bug. Just a user who don't read. Closing

**Closed by OscarAkaElvis** 2024-09-28 15:45 UTC

**Comment by MrBlaZe404** [comment] 2024-09-28 16:07
> Please, give more details. Saying that your airgeddon version is latest is like not saying anything. Latest version changes depending on your system, the repositories you are using or the branch you cloned from GitHub. So be specific.
> 
> Regarding the OS version... The same. The more details you provide, more possibilities to help you.
> 
> Regarding BeEF, did you see the option to tell airgeddon where it is located? I bet no. Please, read the options from the menus. That option is precisely for your case, when you install it on a non-commin location, you must specify where it is to the tool.
> 
> In any case, this is not a bug. Just a user who don't read. Closing

Thank you, but can you tell me where this options is? I can't find it.

**Comment by OscarAkaElvis** [comment] 2024-09-28 16:26
It's in the submenú after selecting Evil Twin BeEF attack. Before launching it.
