### ISSUE TITLE
1st time Run & Work Super-Duper but 2nd time not run and show error-Help me 

### ISSUE THREAD

**Issue by kuamit5516** [v1s1t0r1sh3r3/airgeddon#156] opened 2018-07-13 09:22 UTC
1st time use in very happy 
but
2nd time use show this error,s

help me..

i like this tool 

root@kali:~/airgeddon# sudo bash ./airgeddon.sh
./airgeddon.sh: line 4468: unexpected EOF while looking for matching `}'
./airgeddon.sh: line 4469: unexpected token `�' in conditional command
./airgeddon.sh: line 4469: syntax error: unexpected end of file

**Comment by v1s1t0r1sh3r3** [comment] 2018-07-13 16:05
First strange thing I see is launching it using sudo while you already have a root shell (#) ¿?

To continue we should know a lot of stuff... your airgeddon version, your OS version (which I guess is Kali), at what point is breaking (at the beginning? do you see the intro or not?) and what are you doing on first running of airgeddon.

**Comment by kuamit5516** [comment] 2018-07-13 19:04
Yes u r right this is kali linux 64bit 2018 & yes first running of airgeddon .


Im try wifi crack my password first time work im use sudo and working 
then 2nd time error why  i dnt no ?

root@kali:~/airgeddon# sudo bash ./airgeddon.sh
                 ./airgeddon.sh: line 4468: unexpected EOF while looking for matching }' 
                ./airgeddon.sh: line 4469: unexpected token�' in conditional command
./airgeddon.sh: line 4469: syntax error: unexpected end of file

**Comment by kuamit5516** [comment] 2018-07-13 19:07
See --

root@kali:~# cd airgeddon
root@kali:~/airgeddon####  ./airgeddon.sh
-bash: ./airgeddon.sh: Permission denied
root@kali:~/airgeddon# ### bash ./airgeddon.sh
./airgeddon.sh: line 4468: unexpected EOF while looking for matching `}'
./airgeddon.sh: line 4469: unexpected token `�' in conditional command
./airgeddon.sh: line 4469: syntax error: unexpected end of file
root@kali:~/airgeddon# ### sudo bash ./airgeddon.sh
./airgeddon.sh: line 4468: unexpected EOF while looking for matching `}'
./airgeddon.sh: line 4469: unexpected token `�' in conditional command
./airgeddon.sh: line 4469: syntax error: unexpected end of file

**Comment by v1s1t0r1sh3r3** [comment] 2018-07-13 19:13
This sounds like a not airgeddon problem... anyway... which version of airgeddon? opening an issue has a template. This template is for a reason... to avoid this kind of messages from me asking to you the version used. I want to see what is on lines 4468 and 4469 but without the version is impossible because it changes on each version.

**Comment by xtonousou** [comment] 2018-07-14 03:01
@kuamit5516 Can you try running `airgeddon` like below and post the outputs?

```
sudo LC_ALL=en_US.UTF-8 bash /path/to/airgeddon.sh ; echo "${?}"
```

Tell us your `airgeddon`'s and `Kali`'s version too.

**Comment by d0pp1364n63r** [comment] 2018-07-15 05:45
Try and run it as such when you are in the directory airgeddon is cloned in:
"bash airgeddon"
Don't put the "./" before running the script.
Did you clone or download the zip?
Version of Kali and airgeddon?

**Comment by kuamit5516** [comment] 2018-07-17 20:29
im try bash      #d0pp1364n63r

 
root@kali:~/airgeddon# **bash airgeddon.sh**
airgeddon.sh: line 4468: unexpected EOF while looking for matching `}'
airgeddon.sh: line 4469: unexpected token `�' in conditional command
airgeddon.sh: line 4469: syntax error: unexpected end of file



see ....

**Comment by kuamit5516** [comment] 2018-07-17 20:31
@xtonousou 


im try - sudo LC_ALL=en_US.UTF-8 bash /path/to/airgeddon.sh ; echo "${?}"

but not runing

help me 

root@kali:~/airgeddon# bash airgeddon.sh
airgeddon.sh: line 4468: unexpected EOF while looking for matching `}'
airgeddon.sh: line 4469: unexpected token `�' in conditional command
airgeddon.sh: line 4469: syntax error: unexpected end of file
root@kali:~/airgeddon# sudo bash airgeddon.sh
airgeddon.sh: line 4468: unexpected EOF while looking for matching `}'
airgeddon.sh: line 4469: unexpected token `�' in conditional command
airgeddon.sh: line 4469: syntax error: unexpected end of file
root@kali:~/airgeddon# ./\airgeddon.sh
-bash: ./airgeddon.sh: Permission denied
root@kali:~/airgeddon#

**Comment by v1s1t0r1sh3r3** [comment] 2018-07-17 20:33
It looks like your file is corrupt. Download airgeddon again and try again. Last warning. We are going to close this issue because you are not following the policy regarding provide all needed info.

**Comment by kuamit5516** [comment] 2018-07-17 20:36
@v1s1t0r1sh3r3


im try this version - see - https://github.com/v1s1t0r1sh3r3/airgeddon



unexpected - cammand & file .. why ? 

im try new download  ~/airgeddon# 


but same problm -

see -

root@kali:~/airgeddon# bash airgeddon.sh
airgeddon.sh: line 4468: unexpected EOF while looking for matching `}'
airgeddon.sh: line 4469: unexpected token `�' in conditional command
airgeddon.sh: line 4469: syntax error: unexpected end of file
root@kali:~/airgeddon# sudo bash airgeddon.sh
airgeddon.sh: line 4468: unexpected EOF while looking for matching `}'
airgeddon.sh: line 4469: unexpected token `�' in conditional command
airgeddon.sh: line 4469: syntax error: unexpected end of file


help me

**Comment by kuamit5516** [comment] 2018-07-17 20:40
**WoW


finally Work  - #airgeddon - kali linux 64bit 

thanks for help

all**

**Comment by v1s1t0r1sh3r3** [comment] 2018-07-17 20:41
> im try this version - see - https://github.com/v1s1t0r1sh3r3/airgeddon
That is the repository url, there are different versions there. We can suppose that you are using 8.10

It seems you didn't tried what @xtonousou suggested. `/path/to/airgeddon.sh` must be replaced with the correct path pointing where you have airgeddon.sh stored on your hard disk.

**Comment by v1s1t0r1sh3r3** [comment] 2018-07-17 20:42
Ahh ok, I'm gladi it worked but for sure this wasn't an airgeddon problem. If you found the cause post it. Maybe it could help others someday. Closing.

**Closed by v1s1t0r1sh3r3** 2018-07-17 20:42 UTC
Labels: waiting for info

**Comment by kuamit5516** [comment] 2018-07-17 20:43
@xtonousou

thank-q so much ....


have a nice day
