### ISSUE TITLE
Evil Twin attack password not saved to text file: complete fail

### ISSUE THREAD

**Issue by S1CAR1US** [v1s1t0r1sh3r3/airgeddon#165] opened 2018-08-19 05:13 UTC
#### What is your airgeddon version?

<8.11>

#### What is your Linux O.S. and which version?

<uname -a output:  {4.17.0-Kali1-amd64 #1 SMP Debian 4.17.8-1kali1 (2018-07-24) x86_64 GNU/Linux}>

#### Which is the chipset of your wireless card?

<lspci output:  Network Controller: Qualcomm Atheros QCA9565 / AR9565 Wireless Network Adapter (rev 01)>

#### Describe the issue and the steps to reproduce it

<-Used Evil Twin attack without internet access
   -Provided handshake file captured previously
   -Everything worked as expected, host ran and waited for target to connect
   -When target connected and input password, I was notified of password successfully being retrieved and that it had been saved to the text file which I had left as the default recommended location.
   -The text file was indeed saved and the only information that was included was:
       >Date
       >airgeddon.  Captive portal Evil Twin attack captured password
       >BSSID: xx:xx:xx:xx:xx:xx
       >Channel: 1
       >ESSID: "name of target"
       >Two lines of hash marks and then the very thorough information regarding how to donate to the developer.>

Does this imply that I have to donate to be able to retrieve the actual password?  Because that is what my first impression was.  Why is there no password saved to the file?  In a real world scenario you can see how this can be very damaging to the actual chances of a successful penetration.  The chances are very unlikely that someone will fall for a social engineering hack for a second time.  Please advise me if there is any way to recover the password or if the attack was indeed rendered useless due to the script not working as designed.  Thank you and I thought the script was promising up until this point, kind of all for naught if this last little detail doesn't work as planned. /,=

**Comment by v1s1t0r1sh3r3** [comment] 2018-08-19 09:41
Anyway, I must add that I don't like the way you are talking on this issue. Remember that this is a free open source tool. You are not in position to demand anything. Maybe you should reconsider phrases like "kind of all for naught if this last little detail doesn't work as planned" or the "complete fail" on title. Maybe is a complete fail for you or for your concrete case and you can ask for help saying words like "please" and "thank you". We are not here to serve you. I can close the issue instantly and the problem is over for me.

Be careful my friend. First and last warning.

**Comment by S1CAR1US** [comment] 2018-08-20 04:49
If you would like to take another look, here are the exact points that you criticized me for:

 @v1s1t0r1sh3r3 - Remember this is a free open source tool:  
(Clearly I am inquiring about just that without making any type of demands.)

@S1CAR1US > Does this imply that I have to donate to be able to retrieve the actual password? Because that is what my first impression was.

@v1s1t0r1sh3r3 *Maybe you should reconsider phrases like "kind of all for naught if this last little detail doesn't work as planned"

(Not sure if English is your first language, but this just means that in the end, it was not for any profit or gain without referring to any type of financial benefit.  No ill will or harshly intended words here.)

@v1s1t0r1sh3r3 Use words like please, and thank you...

@S1CAR1US> _**Please**_ advise me if there is any way to recover the password
&
> **_Thank you_** and I thought the script was promising up until this point

Anyways I do thank you for your work as a script writer... and appreciate your contributions to the community in any capacity.  Best wishes.

**Comment by v1s1t0r1sh3r3** [comment] 2018-08-26 22:15
Closing due lack of information.

**Closed by v1s1t0r1sh3r3** 2018-08-26 22:15 UTC
Labels: waiting for info

**Comment by sriyana1** [comment] 2018-10-21 11:04
Thanks for your Great Work..  Please help me.. I have the same issue with case above..  Everything work fine until capture password.. No password save, but capture password succes..  I try differrent network, can work fine.  But with this network password fail...

**Comment by v1s1t0r1sh3r3** [comment] 2018-10-21 11:12
We need more data to address this. Otherwise is impossible. Provide all the info... the complete ESSID of the network, maybe the password contain a special char breaking the stuff, who know.... hard to guess.

**Comment by sriyana1** [comment] 2018-10-21 11:14
![2018-10-21 18 11 45](https://user-images.githubusercontent.com/44329946/47266172-0bb6bc00-d55d-11e8-95dd-4b05094fe9fa.jpg)

**Comment by sriyana1** [comment] 2018-10-21 11:16
![2018-10-21 18 14 26](https://user-images.githubusercontent.com/44329946/47266183-36a11000-d55d-11e8-927c-254b6aa54ebb.jpg)

**Comment by sriyana1** [comment] 2018-10-21 13:02
![img_20181021_195002](https://user-images.githubusercontent.com/44329946/47267298-f72df000-d56b-11e8-8bdd-860e8fc38762.jpg)

**Comment by sriyana1** [comment] 2018-10-21 13:05
![img_20181021_193618](https://user-images.githubusercontent.com/44329946/47267319-4116d600-d56c-11e8-8a6a-c74d5a7b47ec.jpg)

**Comment by sriyana1** [comment] 2018-10-21 13:08
![img_20181021_195101](https://user-images.githubusercontent.com/44329946/47267343-b2568900-d56c-11e8-9734-4b86723c058c.jpg)

**Comment by v1s1t0r1sh3r3** [comment] 2018-10-21 13:11
I'm not understanding your last post... first you put a couple of photos on we can see everything is working fine... and the last photo is again an error... ¿?

**Comment by sriyana1** [comment] 2018-10-21 13:15
Thank you very much... Work perfect.. Password can save now.. in picture 1 about issue,password can view... Last picture is Picture number 1.. is the password  22221111... but I'm not sure.. Now the password can save... and is 22221111... Hehehehe... Thank you very much for your help and Great work..

**Comment by muhammedsahil5000** [comment] 2021-05-26 11:51
My evil twin attack is not work finely....
No pop up sites(capitive portal) showing when  victim connect to fake ap on android and pc
Please help me....
