### ISSUE TITLE
Sorry but we can't help you in this way. You are not providing any data. You are just saying "hey, i have an error".

### ISSUE THREAD

**Issue by VladSabra** [v1s1t0r1sh3r3/airgeddon#438] opened 2021-06-04 08:02 UTC
Please Help I tried everything I use Parrot Os .... When i open airgeddon i select my interface then i set it to monitor mode then i launch a handshake(option 5) then i press explore for targets(number 4 in airgeddon menu) a new terminal opens but no targets show even though im using 2.4 ghz and my wifi is 2.4 ghz. I also tried killing check to avoid conflicts still same problem On my network in the virtual machine i have wifi enabled and it says wired connection 1 i went to setting on parrot os virtual machine and set my usb router to remote network still the same issue i tried evil twin attack still nothing shows when exploring for targets. Also rather than showing the name wlan0 it shows as wlx00ea67c0a18 I also tried using aircrack same thing happens.

**Comment by OscarAkaElvis** [comment] 2021-06-04 09:38
whoaaa whoaaa whoaaa.... I see many problems here:

1. You are not filling the issue creation template. When you open an issue is VERY important to us to know the answer of all the questions marked. Operating system, airgeddon version, your card and chipset, etc... and you are providing only OS (Parrot). Usually the issue is closed directly with no answer if you don't fi the requirements to open it.
2. If your card is shown as wlx00ea67c0a18 , it will give you problems. Read the wiki. The FAQ section. You'll find there a lot of answers. For this, this concrete answer: https://github.com/v1s1t0r1sh3r3/airgeddon/wiki/FAQ%20&%20Troubleshooting#my-linux-has-weird-interface-names-like-wlx00c0ca9208dc-instead-of-wlan0-and-im-getting-errors-what-can-i-do
3. Join to our Discord channel. There, you'll find a community to answer your questions much better than opening issues. Invitation link: https://discord.gg/sQ9dgt9

Closing.

**Closed by OscarAkaElvis** 2021-06-04 09:38 UTC
