### ISSUE TITLE
captive portal doesnt redirect clients

### ISSUE THREAD

**Issue by washaqq** [v1s1t0r1sh3r3/airgeddon#186] opened 2018-10-29 00:24 UTC
#### What is your airgeddon version?

8.11
#### What is your Linux O.S. and which version?

Kali linux Rolling
#### Which is the chipset of your wireless card?

intel pro/wireless 3945ABG Golan rev02 which acts like AP point to establish Captive Portal

#### Describe the issue and the steps to reproduce it
airgeddon doesnt redirect clients to captive portal on windows 10, clients used opera, chrome and firefox but did not tried internet explorer, client redirected manually by typing captive portal ip address.

**Comment by v1s1t0r1sh3r3** [comment] 2018-10-29 20:23
This is a duplicate of this: https://github.com/v1s1t0r1sh3r3/airgeddon/issues/171

There is no issue here. Captive portal is very well tested and working fine since a lot of versions. Probably you are trying to enter into https pages instead of entering on http pages. The explanation is on this link. Closing.

**Closed by v1s1t0r1sh3r3** 2018-10-29 20:23 UTC
