### ISSUE TITLE
Hostapd Compatible USB WI-FI Drivers (2018)

### ISSUE THREAD

**Issue by hasanalizxc** [v1s1t0r1sh3r3/airgeddon#183] opened 2018-10-16 21:48 UTC
Dear airgeddon and Github Members,

I read this issue (https://github.com/FluxionNetwork/fluxion/issues/212) and they are saying alfa asus036h is NOT compatible with hostapd. I have 0036H and when i try to create an evil twin, it stucks.

I also used airgeddon but result is same.

Is there any solution fix this? If there is not a solution for this, could you please tell me what is the compatible USB WI-FI adapters with hostapd? I searched on the internet but i couldn't find any new information. They have old models.

Please share your opinions.

**Comment by OscarAkaElvis** [comment] 2018-10-17 07:01
Yeah, airgeddon is using also hostapd for Evil Twins, so you should get the same results if the problem is related to the wireless card. I don't know if there is a solution for this, I don't think so.

I can tell you that I have fully working airgeddon Evil Twin using these adapters:
 - Alfa AWUS036NH 2.4Ghz -> chipset Ralink RT3070
 - Alfa AWUS036NHA 2.4Ghz -> chipset Atheros AR9271
 - Alfa AWUS052NHS 2.4Ghz, 5Ghz ->chipset Ralink RT3572

Beware if you use them inside Virtualbox virtual machines. It is known that Ralink chipsets have some issues on Virtualbox machines. They work flawlessly on Vmware. And Atheros is working good in both systems (Vmware and Virtualbox). And of course if your Linux is native all will work without any problem.

Good luck!! Closing.

**Closed by OscarAkaElvis** 2018-10-17 07:01 UTC
Labels: question
