### ISSUE TITLE
Problem with interface and RTL8812AU driver

### ISSUE THREAD

**Issue by bobob15** [v1s1t0r1sh3r3/airgeddon#259] opened 2019-05-27 13:42 UTC
#### What is your airgeddon version?

9.20-1

#### What is your Linux O.S. and which version?

Kali Linux 2019.2

#### Which is the chipset of your wireless card?

It's the Awus036ACH and RTL8812AU driver

#### Describe the issue and the steps to reproduce it

Hello, after having put my card in monitor mode manually, it is impossible for me to choose it in Airgeddon, I have an error (see picture). I don't know if it's from the drivers or from Airgeddon itself.

Can you help me?

![58192793-e68c5680-7cc1-11e9-901d-32a84ef26ee3](https://user-images.githubusercontent.com/19501429/58423718-10fd5b80-8096-11e9-88fc-64ddbcb3b75a.jpg)

**Comment by Dema323** [comment] 2019-05-27 14:15
Having exactly same issue with AWUS 1900 and [https://aur.archlinux.org/packages/rtl88xxau-aircrack-dkms-git](url) drivers

**Comment by Dema323** [comment] 2019-05-27 14:48
I just ran the same card on my kali linux vm and it works without issues. So its def a driver issue

**Comment by v1s1t0r1sh3r3** [comment] 2019-05-27 17:12
This is duplicated. This topic was already discussed here:

https://github.com/v1s1t0r1sh3r3/airgeddon/issues/185
https://github.com/v1s1t0r1sh3r3/airgeddon/issues/242
https://github.com/v1s1t0r1sh3r3/airgeddon/issues/233
https://github.com/v1s1t0r1sh3r3/airgeddon/issues/203

And probably on more issues...

That problem appeared because some drivers are not following the standards... they set "Auto" as a mode instead of using "Managed" or "Monitor" which is a problem. We are not supporting them. Anyway, the fix is easy... as @Dema323 use a standard driver. I can recommend to you to use the one available by apt using the command `apt install realtek-rtl88xxau-dkms`. Good luck! closing.

**Closed by v1s1t0r1sh3r3** 2019-05-27 17:12 UTC

**Comment by bobob15** [comment] 2019-05-27 17:15
The problem is that the driver "realtek-rtl88xxau-dkms" is unstable under this version...

**Comment by Dema323** [comment] 2019-05-27 19:47
i put these drivers on manjaro [https://github.com/aircrack-ng/rtl8812au](url) and im still having the same issue. I got the right 5.2.20 version. Don't know why this has to be so difficult

**Comment by OscarAkaElvis** [comment] 2019-05-28 05:29
This is why IMO the market must be carefully checked before buying a card. All my cards are 100% compatibles with airmon and there are standard fully working drivers for them.

@Dema323 open an issue on the driver's developer asking for the needed changes in order to use standard nomenclature. Check the standards, as you can see, wireless devices should operate in these main modes: master, managed, monitor, ad-hoc. Auto is not a standard mode... so drivers "inventing" stuff like that are not supported by airgeddon.

It is clear that the issue is not related to airgeddon. Anyway, I'll try to get one RTL8812AU device in order to test all of this stuff.... and I'll try to find a driver fully working for it. Then, I'll package it as a .deb file and we'll set up a github repo with it. Then I'll put a note and a link on the Wiki in order to avoid this kind of issues. I can't promise anything.... but I'll try to do it.

**Comment by Dema323** [comment] 2019-05-28 09:56
I did open an issue with on the driver github, but to be honest he doesn't seem to care. I saw you recommend : apt install realtek-rtl88xxau-dkms on issue #242. What drivers are those ? And where can i find them as i am not using kali linux ?

**Comment by OscarAkaElvis** [comment] 2019-05-28 10:03
It seems that the deb package from kali/parrot repos comes from the repo you pointed out before but the working version is a specific branch (v5.2.20): https://github.com/aircrack-ng/rtl8812au/tree/v5.2.20 

So you can use that branch. Look, extracted from parrot:

![image](https://user-images.githubusercontent.com/5803348/58469808-8faed300-8140-11e9-816d-74948558ec44.png)

Good luck!

**Comment by Dema323** [comment] 2019-05-28 10:12
yep i used that exact branch, still doesn't work for some reason

**Comment by Dema323** [comment] 2019-05-28 12:05
Ok so now i downloaded exactly the drivers on the kali repo. Everything works. Except that i don't pick up as much AP's as i did before and im getting an error when i try to scan the network for targets. "An unexpected error occurred, redirecting to the menu"

**Comment by Dema323** [comment] 2019-05-28 13:44
@OscarAkaElvis What card would you recommend that had a range like the awus1900 and has working drivers ?

**Comment by OscarAkaElvis** [comment] 2019-05-28 15:13
I have some different cards... I recommend this (but is hard to find): AWUS052NHS

It supports 5ghz, is full compatible with aircrack and airmon. Its chipset is Ralink RT3572

**Comment by Dema323** [comment] 2019-05-28 15:16
what about [https://www.amazon.de/gp/product/B01D064VMS/ref=ppx_yo_dt_b_asin_title_o00_s00?ie=UTF8&psc=1](url) ?

**Comment by OscarAkaElvis** [comment] 2019-11-11 21:20
Ding ding ding!!! your dreams come true: https://github.com/OscarAkaElvis/airgeddon_realtek_chipset_fixer

**Comment by bobob15** [comment] 2019-11-25 06:53
Oh thank you so much !!
