### ISSUE TITLE
unexpected error while exploring for target

### ISSUE THREAD

**Issue by hadi2009** [v1s1t0r1sh3r3/airgeddon#368] opened 2020-04-27 04:48 UTC
#### Is your question related to any concrete technology?

Linux
#### Describe your question as detailed as possible

<Hi, I'm trying to learn to hack on Kali Linux on my RPi 4. I launched Airgeddon and chose the following options:
2 (Wlan0)
2 (Monitor mode)
8 (WPS attacks menu)
4 (explore for targets)

Here where the problem starts. Initially, I get

" Exploring for targets option chosen(monitor mode needed)

Selected interface wlan0 is in monitor mode. Exploration can be performed

It seems like this interface was parametrized before. It is not necessary to check again

WPS filter enabled in scan. When started, press [Ctrl+C] to stop ...

Press [Enter] key to continue ..."

but when I click enter again I get

" An unexpected error occurred, redirecting to the menu
Press [Enter] key to continue ..."

I restarted my RPi4 multiple times and repeated the same process multiple times

What am I doing wrong? Thanks in advance>

**Comment by xpz3** [comment] 2020-04-27 08:40
Whats the wireless card and its chipset? Also what's your airgeddon version? You can join airgeddon discord channel for quicker response from staff.
https://discord.gg/sQ9dgt9

**Comment by OscarAkaElvis** [comment] 2020-04-27 08:45
It looks that the xterm window can't be open. Are you sure you have installed xterm and a X window system up and running? maybe you have blocked the connections to it. Try to launch the command `xhost +` before launching airgeddon.

Are you experiencing the problem only on WPS scanning? I mean, another kind of scan is working for you? For example you can test a normal scan on DoS section (option menu 4) and then option 4 again to scan to see if your problem is also there.

Maybe you could also consider to use tmux instead of xterm if your problem is finally related to the X window system. More info here: https://github.com/v1s1t0r1sh3r3/airgeddon/wiki/Options

Anyway, as @xpz3 said, we need more data... chipset, version, etc. Discord is better choice to treat this kind of things.

**Comment by hadi2009** [comment] 2020-04-27 11:08
I am using the internal chip. when I am on the menu where it tells me to chose what interface to work with. next to wlan0 under chipset is says unknown. I am using the latest version. I am also using a wireless mouse and a wired keyboard. i am using kali for RPi4 64 bit.

**Comment by hadi2009** [comment] 2020-04-27 11:09
the built-in internal chip

**Comment by OscarAkaElvis** [comment] 2020-04-27 14:38
as far as i know, the internal wireless cards of raspberrys can't be used for this. not sure if in the new rpi4 the card is supporting monitor mode. Maybe you need just to plug an external usb card to work with.

Anyway, is working for you out of airgeddon? did you try `airmon-ng start wlan0` command? and then if is able to set monitor mode, launch `airodump-ng wlan0mon` . Is that working for you?

**Comment by xpz3** [comment] 2020-04-27 21:44
Closing. The problem is with his chipset. He joined discord and his issue has been discussed there.

**Closed by xpz3** 2020-04-27 21:44 UTC
Labels: invalid

**Comment by carmonkeylab** [comment] 2020-04-29 22:04
kk

**Comment by Drag0n0** [comment] 2021-07-16 02:49
- another problem in this step , i have alfa
--------- 
> 4

**************************** Exploring for targets ***************************** 
Exploring for targets option chosen (monitor mode needed) 

This interface wlan1 is not in monitor mode 
Press [Enter] key to continue...

**Comment by OscarAkaElvis** [comment] 2021-07-16 06:56
omg... really??? I think you should learn to READ, that's all. What is the message telling to you??? and what is supposed to do? maybe set that card in monitor mode before scanning?

Please, join Discord channel and don't spam people here with stuff like that.

**Comment by Drag0n0** [comment] 2021-07-16 12:48
I command airmon-ng start wlan0
Are there another way to able monitore mode

**Comment by OscarAkaElvis** [comment] 2021-07-16 13:18
What?? you should put monitor mode inside the airgeddon menus... if you are doing it on your own out of airgeddon, why to ask on airgeddon github? i'll lock this thread
